src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activated_Percent_HTN__c</fullName>
        <description>Member Activation percentage (for Hypertension)</description>
        <label>Activated Percent (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Activation__c</fullName>
        <description>Member Activation percent (for Diabetes)</description>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Activated Percent (Diabetes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Client_Risk_Notes__c</fullName>
        <description>Place to track details regarding the Account Health Score (green, yellow, red) and possible risks to the account health</description>
        <label>Account Health Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Coverage_Percentage_DM__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Email Coverage Percentage (DM)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Email_Coverage_Percentage_HTN__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Email Coverage Percentage (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Enrollment_Percentage_rPwDs__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Enrollment Percentage (rPwDs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Enrollment_Percentage_rPwHs__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Enrollment Percentage (rPwHs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Usage_Last_30_day_Diabetes__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Usage % Last 30 day (Diabetes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Usage_Last_30_day_HTN__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Usage % Last 30 day (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Scores</relationshipLabel>
        <relationshipName>Health_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <label>Actual Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Health_Segment__c</fullName>
        <label>Health Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Active 30</fullName>
                </value>
                <value>
                    <fullName>Marketing Type (Outreach Stratification)</fullName>
                </value>
                <value>
                    <fullName>Email Coverage</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                </value>
                <value>
                    <fullName>eHba1c Reduction</fullName>
                </value>
                <value>
                    <fullName>ROI Status</fullName>
                </value>
                <value>
                    <fullName>Client Launch Date</fullName>
                </value>
                <value>
                    <fullName>Systolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Diastolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Program Score</fullName>
                </value>
                <value>
                    <fullName>Renewal Timing</fullName>
                </value>
                <value>
                    <fullName>Cross Sells/Expansions</fullName>
                </value>
                <value>
                    <fullName>Client NPS</fullName>
                </value>
                <value>
                    <fullName>Interaction Cadence</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor Interaction/Engagement</fullName>
                </value>
                <value>
                    <fullName>Contract Path/Partner Relationship/Status</fullName>
                </value>
                <value>
                    <fullName>Client Business Health</fullName>
                </value>
                <value>
                    <fullName>Issues</fullName>
                </value>
                <value>
                    <fullName>Competitor w/in account</fullName>
                </value>
                <value>
                    <fullName>Immediate Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                    <isActive>false</isActive>
                    <label>Behavioral Health</label>
                </value>
                <value>
                    <fullName>Diabetes Prevention</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes Prevention</label>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                    <isActive>false</isActive>
                    <label>Weight Management</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/JBCXM__CTA__c.object
<CustomObject>
    <fields>
        <fullName>JBCXM__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call To Actions</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Call To Action</label>
    <nameField>
        <label>Call To Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call To Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountTriggerTest.cls
@isTest
public class AccountTriggerTest {
    
    private static List<Account> getAccountId(){
        Account clientAccount = TestFactory.createClientAccount();
        List<Account> accounts = new List<Account>();
        accounts.add(clientAccount);
        insert accounts; 
        return accounts;
    }
    
    private static List<Account> getAccountIdWithExistingNotes(){
        Account clientAccount = TestFactory.createClientAccount();
        List<Account> Accts=new List<Account>();
        Accts.add(clientAccount); 
        insert Accts; 
        Accts[0].Client_Risk_Notes__c='Unit Testing on Trigger Class';
        update Accts; 
        return Accts;
    }
    
    
    private static List<ContentDocumentLink> getContentDocumentLink(Set<Id> idSet) {
        return [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN :idset];
    }
    
    private static List<ContentNote> getContentNote(set<Id> idSet) {
        return [SELECT Id,Title,Content,TextPreview,OwnerId from ContentNote where Id In: idSet];
    }
    
    
    @isTest
    static void createNewNotes(){
        // New Notes creation testing when account health notes is added for the first time.
        List<Account> Accts=getAccountId();            
        set<Id> acctId=new Set<Id>();      
        Accts[0].Client_Risk_Notes__c='Unit Testing on Trigger Class';
        acctId.add(Accts[0].Id);
        Test.startTest();
        update Accts;
        Test.stopTest();
        
        List<ContentDocumentLink> conDoc=getContentDocumentLink(acctId);
        Set<Id> cLinkId = new Set<Id>();
        System.assertEquals(1, conDoc.size());
        for (ContentDocumentLink cLink: conDoc) {
            cLinkId.add(cLink.ContentDocumentId);
        } 
        
        List<ContentNote> conNote=getContentNote(cLinkId);
        system.assertEquals(1, conNote.size());
        system.assertEquals('Account Health Notes', conNote[0].Title);
        system.assertEquals('Unit Testing on Trigger Class', conNote[0].Content.toString());
        system.assertEquals('Unit Testing on Trigger Class', conNote[0].TextPreview);
        System.assertEquals(System.UserInfo.getUserId(), conNote[0].OwnerId);   
        
    }
    
    @isTest
    static void appendToExistingNotes(){
        // Update notes 
        List<Account> Accts=getAccountIdWithExistingNotes();            
        set<Id> acctId=new Set<Id>();  
        Accts[0].Client_Risk_Notes__c='Append this Notes';
        acctId.add(Accts[0].Id);
        Test.startTest();
        update Accts;
        Test.stopTest();    
        
        
        List<ContentDocumentLink> conDoc=getContentDocumentLink(acctId);
        Set<Id> cLinkId = new Set<Id>();
        System.assertEquals(1, conDoc.size());
        for (ContentDocumentLink cLink: conDoc) {
            cLinkId.add(cLink.ContentDocumentId);
        } 
        
        List<ContentNote> updatedNote=getContentNote(cLinkId);
        
        system.assertEquals(1, updatedNote.size());
        system.assertEquals('Account Health Notes', updatedNote[0].Title);
        system.assertEquals('Unit Testing on Trigger Class Append this Notes', updatedNote[0].TextPreview);
        system.assertEquals(System.UserInfo.getUserId(), updatedNote[0].OwnerId);             
    }
    
    @isTest
    static void healthScoresTest() {
        List<Account> accList = getAccountId();
        for (Account acc : accList) {
            acc.Enrollment_Percentage_rPwDs__c = 100;
            acc.Enrollment_Percentage_rPwHs__c = 100;
            acc.Activation__c = 100;
            acc.Activated_Percent_HTN__c = 100;
            acc.Usage_Last_30_day_Diabetes__c = 100;
            acc.Usage_Last_30_day_HTN__c = 100;
            acc.Email_Coverage_Percentage_DM__c = 100;
            acc.Email_Coverage_Percentage_HTN__c = 100;
        }
        Test.startTest();
        update accList;
        Test.stopTest();
        List<Health_Score__c> hsList = [SELECT Id, Actual_Result__c, Program__c, Health_Segment__c, Account__r.Enrollment_Percentage_rPwDs__c, 
                                        Account__r.Enrollment_Percentage_rPwHs__c, Account__r.Activation__c, Account__r.Activated_Percent_HTN__c, 
                                        Account__r.Usage_Last_30_day_Diabetes__c, Account__r.Usage_Last_30_day_HTN__c, Account__r.Email_Coverage_Percentage_DM__c, 
                                        Account__r.Email_Coverage_Percentage_HTN__c FROM Health_Score__c WHERE Account__c IN :accList 
                                        AND (Health_Segment__c = 'Enrollment' OR Health_Segment__c = 'Activation' OR Health_Segment__c = 'Active 30' 
                                             OR Health_Segment__c = 'Email Coverage')];
        for (Health_Score__c hs : hsList) {
            if (hs.Program__c == 'Diabetes') {
                if (hs.Health_Segment__c == 'Enrollment') {
                    System.assertEquals(String.valueOf(hs.Account__r.Enrollment_Percentage_rPwDs__c), hs.Actual_Result__c);
                }
                else if (hs.Health_Segment__c == 'Activation') {
                    System.assertEquals(String.valueOf(hs.Account__r.Activation__c), hs.Actual_Result__c);
                }
                else if (hs.Health_Segment__c == 'Active 30') {
                    System.assertEquals(String.valueOf(hs.Account__r.Usage_Last_30_day_Diabetes__c), hs.Actual_Result__c);
                }
                else if (hs.Health_Segment__c == 'Email Coverage') {
                    System.assertEquals(String.valueOf(hs.Account__r.Email_Coverage_Percentage_DM__c), hs.Actual_Result__c);
                }
            }
            else if (hs.Program__c == 'Hypertension') {
                if (hs.Health_Segment__c == 'Enrollment') {
                    System.assertEquals(String.valueOf(hs.Account__r.Enrollment_Percentage_rPwHs__c), hs.Actual_Result__c);
                }
                else if (hs.Health_Segment__c == 'Activation') {
                    System.assertEquals(String.valueOf(hs.Account__r.Activated_Percent_HTN__c), hs.Actual_Result__c);
                }
                else if (hs.Health_Segment__c == 'Active 30') {
                    System.assertEquals(String.valueOf(hs.Account__r.Usage_Last_30_day_HTN__c), hs.Actual_Result__c);
                }
                else if (hs.Health_Segment__c == 'Email Coverage') {
                    System.assertEquals(String.valueOf(hs.Account__r.Email_Coverage_Percentage_HTN__c), hs.Actual_Result__c);
                }
            }
        }       
    }
}