src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activated_Percent_HTN__c</fullName>
        <description>Member Activation percentage (for Hypertension)</description>
        <label>Activated Percent (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Activation__c</fullName>
        <description>Member Activation percent (for Diabetes)</description>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Activated Percent (Diabetes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Client_Risk_Notes__c</fullName>
        <description>Place to track details regarding the Account Health Score (green, yellow, red) and possible risks to the account health</description>
        <label>Account Health Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Coverage_Percentage_DM__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Email Coverage Percentage (DM)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Email_Coverage_Percentage_HTN__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Email Coverage Percentage (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Enrollment_Percentage_rPwDs__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Enrollment Percentage (rPwDs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Enrollment_Percentage_rPwHs__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Enrollment Percentage (rPwHs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Usage_Last_30_day_Diabetes__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Usage % Last 30 day (Diabetes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Usage_Last_30_day_HTN__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Usage % Last 30 day (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Scores</relationshipLabel>
        <relationshipName>Health_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <label>Actual Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Fields__c</fullName>
        <label>Display Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Element_Section__c</fullName>
        <label>Element Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Health_Segment__c</fullName>
        <label>Health Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Active 30</fullName>
                </value>
                <value>
                    <fullName>Marketing Type (Outreach Stratification)</fullName>
                </value>
                <value>
                    <fullName>Email Coverage</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                </value>
                <value>
                    <fullName>eHba1c Reduction</fullName>
                </value>
                <value>
                    <fullName>ROI Status</fullName>
                </value>
                <value>
                    <fullName>Client Launch Date</fullName>
                </value>
                <value>
                    <fullName>Systolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Diastolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Program Score</fullName>
                </value>
                <value>
                    <fullName>Renewal Timing</fullName>
                </value>
                <value>
                    <fullName>Cross Sells/Expansions</fullName>
                </value>
                <value>
                    <fullName>Client NPS</fullName>
                </value>
                <value>
                    <fullName>Interaction Cadence</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor Interaction/Engagement</fullName>
                </value>
                <value>
                    <fullName>Contract Path/Partner Relationship/Status</fullName>
                </value>
                <value>
                    <fullName>Client Business Health</fullName>
                </value>
                <value>
                    <fullName>Issues</fullName>
                </value>
                <value>
                    <fullName>Competitor w/in account</fullName>
                </value>
                <value>
                    <fullName>Immediate Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                    <isActive>false</isActive>
                    <label>Behavioral Health</label>
                </value>
                <value>
                    <fullName>Diabetes Prevention</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes Prevention</label>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                    <isActive>false</isActive>
                    <label>Weight Management</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommended_Action_Steps__c</fullName>
        <label>Recommended Action Steps</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <recordTypes>
        <fullName>Account_Health_Score</fullName>
        <active>true</active>
        <label>Account Health Score</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program_Health_Score</fullName>
        <active>true</active>
        <label>Program Health Score</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Health_Score_Elements__mdt.object
<CustomObject>
    <description>This contains different elements captured for Account Health Scores</description>
    <fields>
        <fullName>Display_Fields__c</fullName>
        <label>Display Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Element_Section__c</fullName>
        <label>Element Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Health_Score_Record_Type__c</fullName>
        <label>Health Score Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Health Score</fullName>
                    <default>true</default>
                    <label>Account Health Score</label>
                </value>
                <value>
                    <fullName>Program Health Score</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Segment__c</fullName>
        <label>Health Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member Satisfaction</fullName>
                    <default>true</default>
                    <label>Member Satisfaction</label>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Active 30</fullName>
                </value>
                <value>
                    <fullName>Marketing Type (Outreach Stratification)</fullName>
                </value>
                <value>
                    <fullName>Email Coverage</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                </value>
                <value>
                    <fullName>eHba1c Reduction</fullName>
                </value>
                <value>
                    <fullName>ROI Status</fullName>
                </value>
                <value>
                    <fullName>Client Launch Date</fullName>
                </value>
                <value>
                    <fullName>Systolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Diastolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Program Score</fullName>
                </value>
                <value>
                    <fullName>Renewal Timing</fullName>
                </value>
                <value>
                    <fullName>Cross Sells/Expansions</fullName>
                </value>
                <value>
                    <fullName>Client NPS</fullName>
                </value>
                <value>
                    <fullName>Interaction Cadence</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor Interaction/Engagement</fullName>
                </value>
                <value>
                    <fullName>Contract Path/Partner Relationship/Status</fullName>
                </value>
                <value>
                    <fullName>Client Business Health</fullName>
                </value>
                <value>
                    <fullName>Issues</fullName>
                </value>
                <value>
                    <fullName>Competitor w/in account</fullName>
                </value>
                <value>
                    <fullName>Immediate Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                    <isActive>false</isActive>
                    <label>Behavioral Health</label>
                </value>
                <value>
                    <fullName>Diabetes Prevention</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes Prevention</label>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                    <isActive>false</isActive>
                    <label>Weight Management</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommended_Action_Steps__c</fullName>
        <label>Recommended Action Steps</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Health Score Elements</label>
    <pluralLabel>Health Score Elements</pluralLabel>
</CustomObject>

src/objects/JBCXM__CTA__c.object
<CustomObject>
    <fields>
        <fullName>JBCXM__Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Call To Actions</relationshipLabel>
        <relationshipName>Account</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Call To Action</label>
    <nameField>
        <label>Call To Action Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call To Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountService.cls
/**
* AccountService Class
* 
* 
*/
public class AccountService {
    
    public static final String DEFAULT_CONTENT_NOTE_TITLE = System.Label.Default_Content_Note_Type;
    public static final Id ACCOUNT_HEALTH_SCORE_RECORD_TYPE_ID = Schema.SObjectType.Health_Score__c.getRecordTypeInfosByDeveloperName().get('Account_Health_Score').getRecordTypeId();
    public static final Id PROGRAM_HEALTH_SCORE_RECORD_TYPE_ID = Schema.SObjectType.Health_Score__c.getRecordTypeInfosByDeveloperName().get('Program_Health_Score').getRecordTypeId();
    public static List<ContentNote> nte = new List<ContentNote>();
    public static List<ContentDocumentLink> lnk = new List<ContentDocumentLink>();
    
    public static void autoCreateNote(List<Account> accounts){
        Set<Id>  acctId= new Set<Id>(); 
        Set<Id> contentDocumentIds = new Set<Id>();
        
        for(Account Accts : accounts){   
            acctId.add(Accts.Id);
            //get all contentdocumentids so that you can query on contentnote
            for(ContentDocumentLink conDoc : [SELECT ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId IN : acctId]){
                contentDocumentIds.add(conDoc.ContentDocumentId);
            }
        }
        //get all the content notes using contentDocumentIds
        List<ContentNote> contentNotes = [SELECT Id,Title, Content from ContentNote 
                                          WHERE Title =:DEFAULT_CONTENT_NOTE_TITLE AND Id In: contentDocumentIds ];
        if(!contentNotes.isEmpty()){
            updateExistingNotes(accounts,contentNotes);
        }else{
            addNewNotes(accounts);
        }
    }            
    // this method will update the existing Account Health Notes with new notes
    public static void updateExistingNotes(List<Account> accounts, List<ContentNote> contentNotes){
        string content;           
        for(Account Accts : accounts){
            for(ContentNote contentnote :contentNotes){
                if(contentnote.Title != NULL && contentnote.Title == DEFAULT_CONTENT_NOTE_TITLE){  
                    content=(contentnote.Content.toString() +'<br/>'+'<br/>'+ Accts.Client_Risk_Notes__c);
                    contentnote.Content=blob.valueOf(content);
                    nte.add(contentnote);                           
                }
            }
        } 
        if(!nte.isEmpty()){
            try{
                update nte;
            }catch(DmlException e){
                System.debug(e.getMessage());
            }
        }
        nte.clear();
    }
    
    // this method will add new Account Health Notes to an Account 
    public static void addNewNotes(List<Account> accounts){
        
        for(Account Accts : accounts){
            ContentNote cnt = new ContentNote();  
            cnt.Content = Blob.valueof(Accts.Client_Risk_Notes__c);
            cnt.Title = DEFAULT_CONTENT_NOTE_TITLE ;
            nte.add(cnt);
        } 
        if(!nte.isEmpty()){
            insert nte;
        }
        for(Account Accts : accounts){
            ContentDocumentLink clnk = new ContentDocumentLink();
            clnk.LinkedEntityId = Accts.Id;
            clnk.ContentDocumentId = nte[0].Id;
            clnk.ShareType = 'V';
            clnk.Visibility='AllUsers';
            lnk.add(clnk);
        }
        if(!lnk.isEmpty()){
            try{
                insert lnk;
            }catch(DmlException e){
                System.debug(e.getMessage());
            }
        }  
        nte.clear();
        lnk.clear();
    }
    public static void createHealthScores(List<Account> accList) {
        List<Health_Score__c> hsListToCreate = new List<Health_Score__c>();
        
        Health_Score_Elements__mdt[] hsElementsMDT = [SELECT Id, Element_Section__c, Health_Score_Record_Type__c, 
                                                      Health_Segment__c, Program__c, Recommended_Action_Steps__c, Sort_Order__c, Display_Fields__c FROM Health_Score_Elements__mdt];
        
        for (Account acc : accList) {
            for (Health_Score_Elements__mdt hsMdt: hsElementsMDT) {
                Health_Score__c hs = new Health_Score__c();
                hs.Account__c = acc.Id;
                hs.Health_Segment__c = hsMdt.Health_Segment__c;
                if (hsMdt.Health_Score_Record_Type__c == 'Program Health Score') {
                    hs.RecordTypeId = PROGRAM_HEALTH_SCORE_RECORD_TYPE_ID;
                    hs.Program__c = hsMdt.Program__c;
                }
                else {
                    hs.RecordTypeId = ACCOUNT_HEALTH_SCORE_RECORD_TYPE_ID;
                }
                hs.Element_Section__c = hsMdt.Element_Section__c;
                hs.Recommended_Action_Steps__c = hsMdt.Recommended_Action_Steps__c;
                hs.Sort_Order__c = hsMdt.Sort_Order__c;
                hs.Display_Fields__c = hsMdt.Display_Fields__c;
                hsListToCreate.add(hs);
            }
        }
        if (!hsListToCreate.isEmpty()) {
            Insert hsListToCreate;
        }       
    }
    
    public static void updateHealthScores (List<Account> newAccounts, Map<Id, Account> oldAccounts) {
        List<Health_Score__c> hsListToUpdate = new List<Health_Score__c>();
        List<Health_Score__c> hsList = [SELECT Id, RecordType.Name, Program__c, Health_Segment__c, Actual_Result__c, Account__r.Enrollment_Percentage_rPwDs__c,
                                        Account__r.Enrollment_Percentage_rPwHs__c, Account__r.Activation__c, Account__r.Activated_Percent_HTN__c, 
                                        Account__r.Usage_Last_30_day_Diabetes__c, Account__r.Usage_Last_30_day_HTN__c,
                                        Account__r.Email_Coverage_Percentage_DM__c, Account__r.Email_Coverage_Percentage_HTN__c
                                        FROM Health_Score__c WHERE Account__c IN :newAccounts AND RecordType.Name != 'Account Health Score'];
        if (hsList.size() > 0) {
            for (Health_Score__c hs : hsList) {
                if (hs.Account__r.Enrollment_Percentage_rPwDs__c != null && hs.Account__r.Enrollment_Percentage_rPwDs__c != oldAccounts.get(hs.Account__c).Enrollment_Percentage_rPwDs__c
                    && hs.Health_Segment__c == 'Enrollment' && hs.Program__c == 'Diabetes') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Enrollment_Percentage_rPwDs__c);
                    }
                if (hs.Account__r.Enrollment_Percentage_rPwHs__c != null && hs.Account__r.Enrollment_Percentage_rPwHs__c != oldAccounts.get(hs.Account__c).Enrollment_Percentage_rPwHs__c
                    && hs.Health_Segment__c == 'Enrollment' && hs.Program__c == 'Hypertension') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Enrollment_Percentage_rPwHs__c);
                    }
                if (hs.Account__r.Activation__c != null && hs.Account__r.Activation__c != oldAccounts.get(hs.Account__c).Activation__c
                    && hs.Health_Segment__c == 'Activation' && hs.Program__c == 'Diabetes') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Activation__c);
                    }
                if (hs.Account__r.Activated_Percent_HTN__c != null && hs.Account__r.Activated_Percent_HTN__c != oldAccounts.get(hs.Account__c).Activated_Percent_HTN__c
                    && hs.Health_Segment__c == 'Activation' && hs.Program__c == 'Hypertension') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Activated_Percent_HTN__c);
                    }
                if (hs.Account__r.Usage_Last_30_day_Diabetes__c != null && hs.Account__r.Usage_Last_30_day_Diabetes__c != oldAccounts.get(hs.Account__c).Usage_Last_30_day_Diabetes__c
                    && hs.Health_Segment__c == 'Active 30' && hs.Program__c == 'Diabetes') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Usage_Last_30_day_Diabetes__c);
                    }
                if (hs.Account__r.Usage_Last_30_day_HTN__c != null && hs.Account__r.Usage_Last_30_day_HTN__c != oldAccounts.get(hs.Account__c).Usage_Last_30_day_HTN__c
                    && hs.Health_Segment__c == 'Active 30' && hs.Program__c == 'Hypertension') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Usage_Last_30_day_HTN__c);
                    }
                if (hs.Account__r.Email_Coverage_Percentage_DM__c != null && hs.Account__r.Email_Coverage_Percentage_DM__c != oldAccounts.get(hs.Account__c).Email_Coverage_Percentage_DM__c
                    && hs.Health_Segment__c == 'Email Coverage' && hs.Program__c == 'Diabetes') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Email_Coverage_Percentage_DM__c);
                    }
                if (hs.Account__r.Email_Coverage_Percentage_HTN__c != null && hs.Account__r.Email_Coverage_Percentage_HTN__c != oldAccounts.get(hs.Account__c).Email_Coverage_Percentage_HTN__c
                    && hs.Health_Segment__c == 'Email Coverage' && hs.Program__c == 'Hypertension') {
                        hs.Actual_Result__c = String.valueOf(hs.Account__r.Email_Coverage_Percentage_HTN__c);
                    }
                hsListToUpdate.add(hs);
            }
        }
        if (!hsListToUpdate.isEmpty()) {
            try {
                update hsListToUpdate;
            }
            catch(DMLException e) {
                system.debug('The following exception has occurred:' + e.getMessage());
            }
        }
    }
}