src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Marketing</fullName>
        <active>false</active>
        <label>Marketing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <label>Actual Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Business_Health__c</fullName>
        <label>Client Business Health</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Growing</fullName>
                </value>
                <value>
                    <fullName>Stable</fullName>
                </value>
                <value>
                    <fullName>Declining</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_NPS__c</fullName>
        <label>Client NPS</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Client_doesn_t_complete_survey__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Client doesn&apos;t complete survey</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Competitor_w_in_account__c</fullName>
        <label>Competitor w/in account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Path_Status__c</fullName>
        <label>Contract Path Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Green Partner</fullName>
                </value>
                <value>
                    <fullName>Yellow Partner</fullName>
                </value>
                <value>
                    <fullName>Red/Black Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cross_Sells_Expansions__c</fullName>
        <label>Cross Sells/Expansions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion/cross sell opp/no additional programs to sell</fullName>
                </value>
                <value>
                    <fullName>On path to discussion</fullName>
                </value>
                <value>
                    <fullName>Partnership does not allow expansion</fullName>
                </value>
                <value>
                    <fullName>Client declined discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Diastolic_BP_Reduction__c</fullName>
        <label>Diastolic BP Reduction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Executive_Sponsor_Interaction_Engagement__c</fullName>
        <label>Executive Sponsor Interaction/Engagement</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Seat at executive sponsor table</fullName>
                </value>
                <value>
                    <fullName>Livongo executive relationship</fullName>
                </value>
                <value>
                    <fullName>Client Advisory Board</fullName>
                </value>
                <value>
                    <fullName>Operational engagement</fullName>
                </value>
                <value>
                    <fullName>Reference/case study/white paper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Segment__c</fullName>
        <label>Health Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Active 30</fullName>
                </value>
                <value>
                    <fullName>Marketing Type (Outreach Stratification)</fullName>
                </value>
                <value>
                    <fullName>Email Coverage</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                </value>
                <value>
                    <fullName>eHba1c Reduction</fullName>
                </value>
                <value>
                    <fullName>ROI Status</fullName>
                </value>
                <value>
                    <fullName>Client Launch Date</fullName>
                </value>
                <value>
                    <fullName>Systolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Diastolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Program Score</fullName>
                </value>
                <value>
                    <fullName>Renewal Timing</fullName>
                </value>
                <value>
                    <fullName>Cross Sells/Expansions</fullName>
                </value>
                <value>
                    <fullName>Client NPS</fullName>
                </value>
                <value>
                    <fullName>Interaction Cadence</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor Interaction/Engagement</fullName>
                </value>
                <value>
                    <fullName>Contract Path/Partner Relationship/Status</fullName>
                </value>
                <value>
                    <fullName>Client Business Health</fullName>
                </value>
                <value>
                    <fullName>Issues</fullName>
                </value>
                <value>
                    <fullName>Competitor w/in account</fullName>
                </value>
                <value>
                    <fullName>Immediate Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Immediate_Action_Needed__c</fullName>
        <label>Immediate Action Needed</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Merger</fullName>
                </value>
                <value>
                    <fullName>Breach of Contract</fullName>
                </value>
                <value>
                    <fullName>Other Nuclear Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interaction_Cadence__c</fullName>
        <label>Interaction Cadence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting established cadence</fullName>
                </value>
                <value>
                    <fullName>No meeting cadence/consistently cancels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issues__c</fullName>
        <label>Issues</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing Issues</fullName>
                </value>
                <value>
                    <fullName>Data Issues</fullName>
                </value>
                <value>
                    <fullName>Billing Issues</fullName>
                </value>
                <value>
                    <fullName>Eligibility Issues</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Satisfaction__c</fullName>
        <label>Member Satisfaction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Participating_in_any_optimized_campaigns__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Participating in any optimized campaigns</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Population_Refresh__c</fullName>
        <label>Population Refresh</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>within 3 months</fullName>
                </value>
                <value>
                    <fullName>&gt; 3 months ago</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                    <isActive>false</isActive>
                    <label>Behavioral Health</label>
                </value>
                <value>
                    <fullName>Diabetes Prevention</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes Prevention</label>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                    <isActive>false</isActive>
                    <label>Weight Management</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROI_Status_DM__c</fullName>
        <label>ROI Status - DM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client &lt;1.25 years on program or partnership doesn&apos;t allow ROI</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 with 100 activated, claims based completed</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 with 100 activated, fitch mode or BOB</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 years with no ROI completed</fullName>
                </value>
                <value>
                    <fullName>Client ROI completed but results were negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROI_Status_HTN__c</fullName>
        <label>ROI Status - HTN</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client &lt;1.25 years on program or partnership doesn&apos;t allow ROI</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 with 100 activated, claims based completed</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 years with no ROI completed</fullName>
                </value>
                <value>
                    <fullName>Client &gt; 1.25 years with ROI completed but negative results</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Systolic_BP_Reduction__c</fullName>
        <label>Systolic BP Reduction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>eHba1c_Reduction__c</fullName>
        <label>eHba1c Reduction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <recordTypes>
        <fullName>Account_Health_Score</fullName>
        <active>true</active>
        <label>Account Health Score</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program_Health_Score</fullName>
        <active>true</active>
        <label>Program Health Score</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HealthScoreService.cls
public class HealthScoreService {
    public static final Id ACCOUNT_HEALTH_SCORE_RT = Schema.SObjectType.Health_Score__c.getRecordTypeInfosByDeveloperName().get('Account_Health_Score').getRecordTypeId();
    public static final Id PROGRAM_HEALTH_SCORE_RT = Schema.SObjectType.Health_Score__c.getRecordTypeInfosByDeveloperName().get('Program_Health_Score').getRecordTypeId();
    
    public static void calculateScores(List<Health_Score__c> hsList) {
        List<Health_Score__c> accountHealthScoresToUpdate = new List<Health_Score__c>();
        List<Health_Score__c> dmHealthScoresToUpdate = new List<Health_Score__c>();
        List<Health_Score__c> htnHealthScoresToUpdate = new List<Health_Score__c>();
        for (Health_Score__c hs: hsList) {
            if (hs.RecordTypeId == ACCOUNT_HEALTH_SCORE_RT) {
                accountHealthScoresToUpdate.add(hs);
            }
            else if (hs.RecordTypeId == PROGRAM_HEALTH_SCORE_RT && hs.Program__c != Null && hs.Program__c == 'Diabetes') {
                dmHealthScoresToUpdate.add(hs);
            }
            else if (hs.RecordTypeId == PROGRAM_HEALTH_SCORE_RT && hs.Program__c != Null && hs.Program__c == 'Hypertension') {
                htnHealthScoresToUpdate.add(hs);
            }
        }
        if (!accountHealthScoresToUpdate.isEmpty()) {
            updateAccountScores(accountHealthScoresToUpdate);
        }
        if (!dmHealthScoresToUpdate.isEmpty()) {
            updateDMScores(dmHealthScoresToUpdate);
        }
        if (!htnHealthScoresToUpdate.isEmpty()) {
            updateHTNScores(htnHealthScoresToUpdate);
        }
    }
    public static void updateAccountScores(List<Health_Score__c> listOfHealthScores) {
        for (Health_Score__c hs : listOfHealthScores) {
            String healthSegment = hs.Health_Segment__c;
            switch on healthSegment {
                when 'Program Score' {
                    if (String.IsNotBlank(hs.Actual_Result__c)) {
                        Decimal programScore = Decimal.valueOf(hs.Actual_Result__c);
                        if (programScore >= 75) {
                            hs.Score__c = 25;
                        }
                        else if (programScore >= 60 && programScore <= 74) {
                            hs.Score__c = 15;
                        }
                        else {
                            hs.Score__c = 0;
                        }
                    }
                }
                when 'Renewal Timing' {
                    if (hs.Actual_Result__c == '<6 months') {
                        hs.Score__c = 0;
                    }
                    else if (hs.Actual_Result__c == '6 months - 1 year') {
                        hs.Score__c = 10;
                    }
                    else if (hs.Actual_Result__c == '>1 year') {
                        hs.Score__c = 15;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Cross Sells/Expansions'{
                    if (hs.Cross_Sells_Expansions__c == 'Expansion/cross sell opp/no additional programs to sell') {
                        hs.Score__c = 10;
                    }
                    else if (hs.Cross_Sells_Expansions__c == 'On path to discussion') {
                        hs.Score__c = 5;
                    }
                    else if(hs.Cross_Sells_Expansions__c == 'Partnership does not allow expansion') {
                        hs.Score__c = 0;
                    }
                    else if (hs.Cross_Sells_Expansions__c == 'Client declined discussion') {
                        hs.Score__c = -10;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Client NPS' {
                    if (hs.Client_doesn_t_complete_survey__c) {
                        hs.Score__c = 5;
                    }
                    else if (hs.Client_NPS__c > 55) {
                        hs.Score__c = 5;
                    }
                    else if (hs.Client_NPS__c >= 40 && hs.Client_NPS__c <= 55) {
                        hs.Score__c = 2;
                    }
                    else if (hs.Client_NPS__c < 40) {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Client Business Health' {
                    if (hs.Client_Business_Health__c == 'Growing') {
                        hs.Score__c = 15;
                    }
                    else if (hs.Client_Business_Health__c == 'Stable') {
                        hs.Score__c = 10;
                    }
                    else if (hs.Client_Business_Health__c == 'Declining') {
                        hs.Score__c = -10;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Interaction Cadence' {
                    if (hs.Interaction_Cadence__c == 'Meeting established cadence') {
                        hs.Score__c = 10;
                    }
                    else if (hs.Interaction_Cadence__c == 'No meeting cadence/consistently cancels') {
                        hs.Score__c = -10;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Executive Sponsor Interaction/Engagement' {
                    String exeSpnsrIntrctnEngmnt = hs.Executive_Sponsor_Interaction_Engagement__c;
                    if (String.isNotBlank(exeSpnsrIntrctnEngmnt)) {
                        List<String> exeSpnsrIntrctnEngmntList = exeSpnsrIntrctnEngmnt.split(';');
                        if (exeSpnsrIntrctnEngmntList.size() > 0) {
                            hs.Score__c = 3 * exeSpnsrIntrctnEngmntList.size();
                        }
                        else {
                            hs.Score__c = 0;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                
                when 'Contract Path/Partner Relationship/Status' {
                    if (hs.Contract_Path_Status__c == 'Green Partner') {
                        hs.Score__c = 5;
                    }
                    else if (hs.Contract_Path_Status__c == 'Yellow partner') {
                        hs.Score__c = 2;
                    }
                    else if (hs.Contract_Path_Status__c == 'Red/black partner') {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Issues' {
                    String issues = hs.Issues__c;
                    if (String.isNotBlank(issues)) {
                        List<String> issueList = issues.split(';');
                        if (issueList.size() > 0) {
                            hs.Score__c = -15;
                        }
                        else {
                            hs.Score__c = 0;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Competitor w/in account' {
                    if (hs.Competitor_w_in_account__c == 'Yes') {
                        hs.Score__c = -15;
                    }
                    else if (hs.Competitor_w_in_account__c == 'No') {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Immediate Action Needed' {
                    String imActionNeeded = hs.Immediate_Action_Needed__c;
                    if (String.isNotBlank(imActionNeeded)) {
                        List<String> imActionNeededList = imActionNeeded.split(';');
                        if (imActionNeededList.size() > 0) {
                            hs.Score__c = -20;
                        }
                        else {
                            hs.Score__c = 0;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
            }   
        }
    }
    
    public static void updateDMScores(List<Health_Score__c> listOfHealthScores) {
        for (Health_Score__c hs : listOfHealthScores) {
            String healthSegment = hs.Health_Segment__c;
            switch on healthSegment {
                when 'Member Satisfaction' {
                    if (hs.Member_Satisfaction__c > 60) {
                        hs.Score__c = 10;
                    }
                    else if (hs.Member_Satisfaction__c >= 40 && hs.Member_Satisfaction__c <= 60) {
                        hs.Score__c = 5;
                    }
                    else if (hs.Member_Satisfaction__c < 40) {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Enrollment' {
                    if (String.isNotBlank(hs.Actual_Result__c)) {
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue >= 30) {
                            hs.Score__c = 20;
                        }
                        else if (actualResultValue >= 20 && actualResultValue <= 29) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue < 20) {
                            hs.Score__c = -10;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Activation' {
                    if (String.isNotBlank(hs.Actual_Result__c)) {
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue > 75) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue >= 65 && actualResultValue <= 75) {
                            hs.Score__c = 5;
                        }
                        else if (actualResultValue < 65) {
                            hs.Score__c = -10;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Active 30' {
                    if(String.isNotBlank(hs.Actual_Result__c)){
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue > 75) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue >= 65 && actualResultValue <= 75) {
                            hs.Score__c = 5;
                        }
                        else if (actualResultValue < 65) {
                            hs.Score__c = -10;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Marketing Type (Outreach Stratification)' {
                    if (hs.Actual_Result__c == 'A') {
                        hs.Score__c = 5;
                    }
                    else if (hs.Actual_Result__c == 'B') {
                        hs.Score__c = 2;
                    }
                    else if (hs.Actual_Result__c == 'C') {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                    if (hs.Participating_in_any_optimized_campaigns__c) {
                        hs.Score__c += 5;
                    }
                }
                when 'Email Coverage' {
                    if (String.IsNotBlank(hs.Actual_Result__c)) {
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue > 40) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue >= 20 && actualResultValue <= 40) {
                            hs.Score__c = 5;
                        }
                        else if (actualResultValue < 20 && actualResultValue > 0) {
                            hs.Score__c = 2;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Population Refresh' {
                    if (hs.Population_Refresh__c == 'within 3 months') {
                        hs.Score__c = 10;
                    }
                    else if (hs.Population_Refresh__c == '> 3 months ago') {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'eHba1c Reduction' {
                    if (hs.eHba1c_Reduction__c > 0.5) {
                        hs.Score__c = 15;
                    }
                    else if (hs.eHba1c_Reduction__c >= 0.3 && hs.eHba1c_Reduction__c <= 0.5) {
                        hs.Score__c = 10;
                    }
                    else if (hs.eHba1c_Reduction__c >= 0 && hs.eHba1c_Reduction__c <= 0.29) {
                        hs.Score__c = 5;
                    }
                    else if (hs.eHba1c_Reduction__c < 0) {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'ROI Status' {
                    if (hs.ROI_Status_DM__c == 'Client <1.25 years on program or partnership doesn\'t allow ROI' ||
                        hs.ROI_Status_DM__c == 'Client >1.25 with 100 activated, claims based completed') {
                            hs.Score__c = 5;
                       }
                    else if (hs.ROI_Status_DM__c == 'Client >1.25 with 100 activated, fitch mode or BOB') {
                        hs.Score__c = 3;
                    }
                    else if (hs.ROI_Status_DM__c == 'Client >1.25 years with no ROI completed') {
                        hs.Score__c = -10;
                    }
                    else if (hs.ROI_Status_DM__c == 'Client ROI completed but results were negative') {
                        hs.Score__c = -20;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
            }
        }
    }
    
    public static void updateHTNScores(List<Health_Score__c> listOfHealthScores){
        for (Health_Score__c hs : listOfHealthScores) {
            String healthSegment = hs.Health_Segment__c;
            switch on healthSegment {
                when 'Member Satisfaction' {
                    if (hs.Member_Satisfaction__c > 60) {
                        hs.Score__c = 10;
                    }
                    else if (hs.Member_Satisfaction__c >= 40 && hs.Member_Satisfaction__c <= 60) {
                        hs.Score__c = 5;
                    }
                    else if (hs.Member_Satisfaction__c < 40) {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Enrollment' {
                    if(String.isNotBlank(hs.Actual_Result__c)){
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue >= 20) {
                            hs.Score__c = 20;
                        }
                        else if (actualResultValue >= 10 && actualResultValue <= 20) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue < 10) {
                            hs.Score__c = -10;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Activation' {
                    if (String.isNotBlank(hs.Actual_Result__c)) {
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue > 70) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue >= 60 && actualResultValue <= 70) {
                            hs.Score__c = 5;
                        }
                        else if (actualResultValue < 60) {
                            hs.Score__c = -10;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Active 30' {
                    if (String.isNotBlank(hs.Actual_Result__c)) {
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue > 70) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue >= 60 && actualResultValue <= 70) {
                            hs.Score__c = 5;
                        }
                        else if (actualResultValue < 60) {
                            hs.Score__c = -10;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Marketing Type (Outreach Stratification)' {
                    if (hs.Actual_Result__c == 'A') {
                        hs.Score__c = 5;
                    }
                    else if (hs.Actual_Result__c == 'B') {
                        hs.Score__c = 2;
                    }
                    else if (hs.Actual_Result__c == 'C') {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                    if (hs.Participating_in_any_optimized_campaigns__c) {
                        hs.Score__c += 5;
                    }
                }
                when 'Email Coverage' {
                    if (String.IsNotBlank(hs.Actual_Result__c)) {
                        Decimal actualResultValue = Decimal.valueOf(hs.Actual_Result__c);
                        if (actualResultValue > 40) {
                            hs.Score__c = 10;
                        }
                        else if (actualResultValue >= 20 && actualResultValue <= 40) {
                            hs.Score__c = 5;
                        }
                        else if (actualResultValue < 20 && actualResultValue > 0) {
                            hs.Score__c = 2;
                        }
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Population Refresh' {
                    if (hs.Population_Refresh__c == 'within 3 months') {
                        hs.Score__c = 10;
                    }
                    else if (hs.Population_Refresh__c == '> 3 months ago') {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Systolic BP Reduction' {
                    if (hs.Systolic_BP_Reduction__c >= 8) {
                        hs.Score__c = 15;
                    }
                    else if (hs.Systolic_BP_Reduction__c >= 3 && hs.Systolic_BP_Reduction__c <= 7) {
                        hs.Score__c = 10;
                    }
                    else if (hs.Systolic_BP_Reduction__c >= 1 && hs.Systolic_BP_Reduction__c <= 2) {
                        hs.Score__c = 5;
                    }
                    else if (hs.Systolic_BP_Reduction__c <= 0) {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'Diastolic BP Reduction' {
                    if (hs.Diastolic_BP_Reduction__c >= 5) {
                        hs.Score__c = 15;
                    }
                    else if (hs.Diastolic_BP_Reduction__c >= 2 && hs.Diastolic_BP_Reduction__c <= 4) {
                        hs.Score__c = 10;
                    }
                    else if (hs.Diastolic_BP_Reduction__c >= 1 && hs.Diastolic_BP_Reduction__c < 2) {
                        hs.Score__c = 5;
                    }
                    else if (hs.Diastolic_BP_Reduction__c <= 0) {
                        hs.Score__c = 0;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
                when 'ROI Status' {
                    if (hs.ROI_Status_HTN__c == 'Client <1.25 years on program or partnership doesn\'t allow ROI' ||
                        hs.ROI_Status_HTN__c == 'Client >1.25 with 100 activated, claims based completed') {
                            hs.Score__c = 5;
                       }
                    else if (hs.ROI_Status_HTN__c == 'Client >1.25 years with no ROI completed') {
                        hs.Score__c = -10;
                    }
                    else if (hs.ROI_Status_HTN__c == 'Client > 1.25 years with ROI completed but negative results') {
                        hs.Score__c = -20;
                    }
                    else {
                        hs.Score__c = 0;
                    }
                }
            }
        }
    }
}