src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Type__c</fullName>
        <description>Field that indicates whether an account is a prospect, a client (and where they&apos;re at in the onboarding process), or former client</description>
        <label>Account Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Prospecting</fullName>
                    <default>true</default>
                    <label>Prospecting</label>
                </value>
                <value>
                    <fullName>Prospecting - Expressed Interest</fullName>
                </value>
                <value>
                    <fullName>Prospecting – Not Currently Interested</fullName>
                </value>
                <value>
                    <fullName>Engaging</fullName>
                </value>
                <value>
                    <fullName>Client</fullName>
                </value>
                <value>
                    <fullName>Former Client</fullName>
                </value>
                <value>
                    <fullName>Disqualified</fullName>
                </value>
                <value>
                    <fullName>Active Partner</fullName>
                </value>
                <value>
                    <fullName>Study</fullName>
                </value>
                <value>
                    <fullName>Client - Downmarket Through Payer / ASO</fullName>
                    <isActive>false</isActive>
                    <label>Client - Downmarket Through Payer / ASO</label>
                </value>
                <value>
                    <fullName>Client - Impending Termination</fullName>
                    <isActive>false</isActive>
                    <label>Client - Impending Termination</label>
                </value>
                <value>
                    <fullName>Client - Launched</fullName>
                    <isActive>false</isActive>
                    <label>Client - Launched</label>
                </value>
                <value>
                    <fullName>Client - Launched +90 Days</fullName>
                    <isActive>false</isActive>
                    <label>Client - Launched +90 Days</label>
                </value>
                <value>
                    <fullName>Client - ON HOLD</fullName>
                    <isActive>false</isActive>
                    <label>Client - ON HOLD</label>
                </value>
                <value>
                    <fullName>Client - Onboarding</fullName>
                    <isActive>false</isActive>
                    <label>Client - Onboarding</label>
                </value>
                <value>
                    <fullName>Client - Ongoing Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Client - Ongoing Delivery</label>
                </value>
                <value>
                    <fullName>Marketing Partner</fullName>
                    <isActive>false</isActive>
                    <label>Marketing Partner</label>
                </value>
                <value>
                    <fullName>Partner</fullName>
                    <isActive>false</isActive>
                    <label>Partner</label>
                </value>
                <value>
                    <fullName>Prospect</fullName>
                    <isActive>false</isActive>
                    <label>Prospect</label>
                </value>
                <value>
                    <fullName>Prospect - Expressed Interest</fullName>
                    <isActive>false</isActive>
                    <label>Prospect - Expressed Interest</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Client_Account</fullName>
        <active>true</active>
        <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
        <label>Client Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Scores</relationshipLabel>
        <relationshipName>Health_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HealthScoresBatchTest.cls
@isTest
private class HealthScoresBatchTest {
    @testSetup 
    static void setup() {
        List<Account> accounts = new List<Account>();
        for (Integer i=0; i<10; i++) {
            Account testAccount = new Account();
            testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
            testAccount.Name = 'Test Batch Account' + i;
            testAccount.Type = 'Self Funded Employer';
            testAccount.Account_Type__c = 'Client';
            accounts.add(testAccount);
        }
        insert accounts;
    }
    
    static testmethod void test() {  
        List<Account> accList = [SELECT Id FROM Account WHERE Name LIKE 'Test Batch Account%'];
        Test.startTest();
        HealthScoresBatch caub = new HealthScoresBatch();
        Id batchId = Database.executeBatch(caub);
        Test.stopTest();
        System.assertEquals(640, [SELECT count() FROM Health_Score__c WHERE Account__c IN: accList]);
    }
     
}