src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Covered_Lives__c</fullName>
        <description>Number of total covered lives</description>
        <label>Covered Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <recordTypes>
        <fullName>Client_Account</fullName>
        <active>true</active>
        <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
        <label>Client Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Competitor_Account</fullName>
        <active>true</active>
        <description>Non-sales account associated with competitive vendors</description>
        <label>Competitor Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Downmarket_Client</fullName>
        <active>true</active>
        <description>Child sales account associated with downmarket parent-child relationships</description>
        <label>Downmarket Client</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner_Account</fullName>
        <active>true</active>
        <description>Non-sales account associated with partner relationships (e.g. Health Plans, PBMs, Benefit Consultants)</description>
        <label>Partner Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Auto_Renewal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Auto Renewal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Complete_Per_Legal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete Per Legal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PPPM__c</fullName>
        <description>Integrated with NetSuite and Redshift</description>
        <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
        <label>PPPM</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Participants__c</fullName>
        <label>Participants</label>
        <precision>7</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_End_Date__c</fullName>
        <description>Date the program becomes inactive or expired</description>
        <inlineHelpText>Date the program becomes inactive or expired. Integrated with NetSuite.</inlineHelpText>
        <label>Program End Date</label>
        <type>Date</type>
    </fields>
    <recordTypes>
        <fullName>Client_Overview</fullName>
        <active>true</active>
        <description>Represents the overarching Program Agreement between Livongo and Client + the Client&apos;s specific operational processes</description>
        <label>Client Overview</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program_Overview</fullName>
        <active>true</active>
        <description>Represents the program-specific, Program Schedule under a Program Agreement + the Client&apos;s specific operational processes regarding the program</description>
        <label>Program Overview</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Covered_Lives__c</fullName>
        <formula>Account.Covered_Lives__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Covered Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Pricing_Structure__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
        <label>Pricing Structure</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Pricing Structure is not available.</errorMessage>
            <filterItems>
                <field>Pricing_Structure__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program_ID__c</valueField>
            </filterItems>
            <filterItems>
                <field>Pricing_Structure__c.Price_Book__c</field>
                <operation>equals</operation>
                <valueField>$Source.Price_Book_ID__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pricing_Structure__c</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Participants__c</fullName>
        <inlineHelpText>For new opportunities, enter estimated recruitables or rPwX. For renewals, enter enrolled members.</inlineHelpText>
        <label>Program Participants (rPwX or Enrolled)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Pricing_Structure__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>List_Price__c</fullName>
        <label>List Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Book__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipName>Price_Book_Entry_Variations_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Price_Book_Entry_Variations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Whole_Person_Solution__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only if the program is a WP Solution.</inlineHelpText>
        <label>Whole Person Solution</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>Project_Template_Category__c</fullName>
        <label>Project Template Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ad Hoc Requests</fullName>
                </value>
                <value>
                    <fullName>Data Operations Requests</fullName>
                </value>
                <value>
                    <fullName>Data Science Requests</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>Project Template</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                    <label>Technology Requests</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project_Template_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ad Hoc DS Request</fullName>
                    <isActive>false</isActive>
                    <label>Ad Hoc DS Request</label>
                </value>
                <value>
                    <fullName>Ad Hoc Request</fullName>
                    <isActive>false</isActive>
                    <label>Ad Hoc Request</label>
                </value>
                <value>
                    <fullName>Carrier/Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Client Incentives</fullName>
                </value>
                <value>
                    <fullName>CMC Migration/Deactivation</fullName>
                </value>
                <value>
                    <fullName>Convert SPA to Enterprise</fullName>
                </value>
                <value>
                    <fullName>Cross-Sell (New Program)</fullName>
                </value>
                <value>
                    <fullName>Data Operations Request</fullName>
                    <isActive>false</isActive>
                    <label>Data Operations Request</label>
                </value>
                <value>
                    <fullName>Data Science Request</fullName>
                    <isActive>false</isActive>
                    <label>Data Science Request</label>
                </value>
                <value>
                    <fullName>Data Source Change</fullName>
                </value>
                <value>
                    <fullName>Divestiture</fullName>
                </value>
                <value>
                    <fullName>Enterprise Client Termination</fullName>
                </value>
                <value>
                    <fullName>New Client / Contract Path</fullName>
                </value>
                <value>
                    <fullName>New Client CVS</fullName>
                    <isActive>false</isActive>
                    <label>New Client CVS</label>
                </value>
                <value>
                    <fullName>Population Expansion</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                    <isActive>false</isActive>
                    <label>Population Refresh</label>
                </value>
                <value>
                    <fullName>Report Request</fullName>
                    <isActive>false</isActive>
                    <label>Report Request</label>
                </value>
                <value>
                    <fullName>SPA Carrier/Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>SPA Client Termination</fullName>
                </value>
                <value>
                    <fullName>Whole Person Transition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TaskRayStatus__c</fullName>
        <description>The status of the TaskRay Project</description>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress - On Track</fullName>
                </value>
                <value>
                    <fullName>In Progress - Delayed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                    <isActive>false</isActive>
                    <label>Contracting</label>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                    <isActive>false</isActive>
                    <label>Implementation</label>
                </value>
                <value>
                    <fullName>Launched + 90</fullName>
                    <isActive>false</isActive>
                    <label>Launched + 90</label>
                </value>
                <value>
                    <fullName>Ongoing Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Ongoing Delivery</label>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                    <isActive>false</isActive>
                    <label>Terminated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestFactory.cls
/**
* This class is used to generate test data for unit tests.
* Created : 05/20/2019
* @author Connor Gallaher
*/
@isTest
global class TestFactory {
    //Creates and returns a Program with the specified program name
    public static Product2 createProgram(String programName) {
        Product2 program = new Product2(Name=programName, Family=programName, IsActive=true, ProductCode = programName);
        return program;
    }
    
    //Creates and returns a Whole Person Program with the specified program name
    public static Product2 createWPProgram(String programName, String programFamily) {
        Product2 program = new Product2(Name=programName, Family=programFamily, IsActive=true, ProductCode = programName, Whole_Person_Solution__c = true);
        return program;
    }

    //Creates and returns a Pricebook
    public static Pricebook2 createPricebook() {
        Pricebook2 livongoPricebook = new Pricebook2(Name='Livongo', IsActive=true);
        return livongoPricebook;
    }

    //Creates and returns a PricebookEntry in the Pricebook with the specified Pricebook Id and specified Program Id
    public static PricebookEntry createPricebookEntry(Id pricebookId, Id programId) {
        PricebookEntry pbe = new PricebookEntry(Pricebook2ID = pricebookId, Product2Id = programId, UnitPrice=10, IsActive=true);
        return pbe;
    }

    //Creates and returns an Account with the Client Account Record Type
    public static Account createClientAccount() {
        Account testAccount = new Account();
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
        testAccount.Name = 'Test Client Account';
        testAccount.Type = 'Self Funded Employer';
        testAccount.Covered_Lives__c = 10000;
        return testAccount;
    }
    
    //Creates and returns an Account with the Downmarket Client Record Type
    public static Account createDownmarketClientAccount() {
        Account testAccount = new Account();
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Downmarket_Client').getRecordTypeId();
        testAccount.Name = 'Test Downmarket Client Account';
        testAccount.Type = 'Self Funded Employer';
        testAccount.Covered_Lives__c = 10000;
        return testAccount;
    }

    //Creates and returns an Account with the Competitor Account Record Type
    public static Account createCompetitorAccount() {
        Account testAccount = new Account();
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Competitor_Account').getRecordTypeId();
        testAccount.Name = 'Test Competitor Account';
        testAccount.Type = 'Payer';
        testAccount.Covered_Lives__c = 10000;
        return testAccount;
    }

    //Creates and returns an Account with the Partner Account Record Type
    public static Account createPartnerAccount() {
        Account testAccount = new Account();
        testAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId();
        testAccount.Name = 'Test Partner Account';
        testAccount.Type = 'Payer';
        testAccount.Covered_Lives__c = 10000;
        return testAccount;
    }

    //Creates and returns a new Opportunity
    public static Opportunity createOpportunity() {
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity';
        opp.StageName = 'Selling';
        opp.Type = 'Renewal';
        opp.CloseDate = Date.today().addDays(1);
        return opp;
    }
    
    //Creates and returns a new Opportunity based on the type provided
    public static Opportunity createTypeBasedOpportunity(String type) {
        Opportunity opp = new Opportunity();
        opp.Name = 'Test Opportunity ' + type;
        opp.StageName = 'Selling';
        opp.Type = type;
        opp.CloseDate = Date.today().addDays(1);
        opp.LeadSource = 'Direct Outreach';
        return opp;
    }
    
    //Creates and returns a new Pricing Structure
    public static Pricing_Structure__c createPricingStructure(Id pricebookId, Id programId) {
        Pricing_Structure__c ps = new Pricing_Structure__c();
        ps.Name = 'Standard';
        ps.Price_Book__c = pricebookId;
        ps.Program__c = programId;
        ps.IsActive__c = true;
        ps.List_Price__c = 65;
        return ps;
    }
    
    //Creates and returns a new OpportunityLineItem
    public static OpportunityLineItem createOpportunityLineItem(Id opptyId, Id pbeId) {
        OpportunityLineItem oli = new OpportunityLineItem();
        oli.OpportunityId = opptyId;
        oli.PricebookEntryId = pbeId;
        oli.Quantity = 12;
        oli.Product_Participants__c = 100;
        oli.UnitPrice = 65;
        return oli;
    }

    //Creates and returns a Contract (Client Overview)
    public static Contract createClientOverview() {
        Contract clientOverview = new Contract();
        clientOverview.RecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Client_Overview').getRecordTypeId();
        clientOverview.Status = 'Draft';
        return clientOverview;
    }

    //Creates and returns a Contract (Program Overview)
    public static Contract createProgramOverview() {
        Contract programOverview = new Contract();
        programOverview.RecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Program_Overview').getRecordTypeId();
        programOverview.Status = 'Draft';
        programOverview.Auto_Renewal__c = true;
        programOverview.PPPM__c = 100;
        programOverview.Participants__c = 1000;
        programOverview.Program_End_Date__c = Date.today();
        programOverview.Complete_Per_Legal__c = false;
        return programOverview;
    }
    
    //Creates and returns a TaskRayProject
    public static TASKRAY__Project__c createTaskRayProject() {
        TASKRAY__Project__c project = new TASKRAY__Project__c();
       	project.TaskRayStatus__c = 'Not Started';
        project.Project_Template_Category__c = 'Project Template';
        project.Project_Type__c = 'New Client / Contract Path';
        project.Project_Sub_Type__c = 'Direct > 2,500 Employees';
        return project;
    }

    //Creates and returns a ClientHandoffSummary
    public static Client_Handoff_Summary__c createClientHandoffSummary() {
        Client_Handoff_Summary__c chs = new Client_Handoff_Summary__c();
        return chs;
    }

    //Creates and returns a Contact
    public static Contact createSalesContact() {
        Contact con = new Contact();
        con.FirstName = 'Spider Man';
        con.LastName = 'Marvel';
        con.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Sales_Contact').getRecordTypeId();
        con.Phone = '1234567890';
        con.Email = 'contest@test.com';
        return con;
    }
    
    //Creates and returns a Relationship based on the type
    public static Relationship__c createRelationship(String type) {
        Relationship__c  rel = new Relationship__c();
        rel.RelationshipType__c = type;
        return rel;
    }
    
    //Creates and returns a Client Member Code
    public static ClientMemberCode__c createClientMemberCode(){
        ClientMemberCode__c memberCode= new ClientMemberCode__c();
        memberCode.RecordTypeId=Schema.SObjectType.ClientMemberCode__c.getRecordTypeInfosByDeveloperName().get('ClientMemberCode').getRecordTypeId();
        memberCode.UsedforRegistration__c=true;
        memberCode.ClientMemberCode__c='CMCXYZ9000';     
        return memberCode;
    }
    
    
}