src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Client_Account</fullName>
        <active>true</active>
        <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
        <label>Client Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner_Account</fullName>
        <active>true</active>
        <description>Non-sales account associated with partner relationships (e.g. Health Plans, PBMs, Benefit Consultants)</description>
        <label>Partner Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>This junction object links Client with Partner Accounts, Partner Accounts with Client Opportunities, Client Accounts with Competitor Accounts, and Competitor Accounts with Client Opportunities.</description>
    <fields>
        <fullName>Master_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to either a Partner or Competitor Account for linking to a Client Account.</description>
        <inlineHelpText>Lookup to either a Partner or Competitor Account for linking to a Client Account.</inlineHelpText>
        <label>Master Vendor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Master Vendor Accounts</relationshipLabel>
        <relationshipName>PartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Defines the master account for the Relates To record</description>
        <label>Master Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Master Client Accounts</relationshipLabel>
        <relationshipName>MasterAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <recordTypes>
        <fullName>Contract_Partnership</fullName>
        <active>true</active>
        <description>Partner at the Contract level (Admin Party, Billing Partner, Care Coordinator, Contract Path, Contract Terms, or Data)</description>
        <label>Contract Partnership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RelatedClientAccountsCtrlTest.cls
@isTest
public class RelatedClientAccountsCtrlTest {

    public static final Id PARTNER_ACCOUNT_RT_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId();
    public static final Id CLIENT_ACCOUNT_RT_ID = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
    public static final Id CONTRACT_PARTNERSHIP_RT_ID = Schema.SObjectType.Relationship__c.getRecordTypeInfosByDeveloperName().get('Contract_Partnership').getRecordTypeId();


    public static Account getPartnerAccount() {
        Id partnerAccountRTId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId();
        return [SELECT Id, RecordTypeId, Name FROM Account WHERE RecordTypeId = :PARTNER_ACCOUNT_RT_ID LIMIT 1];
    }

    @TestSetup
    static void setupData() {
        Account partnerAccount = TestFactory.createPartnerAccount();
        insert partnerAccount;
        
        Contract co = TestFactory.createClientOverview();
        co.AccountId = partnerAccount.Id;
        insert co;
    }

    @isTest
    static void getRelatedClientAccountsRelationshipsLinkedToPartnerAccountTest() {
        Account partnerAccount = getPartnerAccount();
        
        List<Relationship__c> relationships = [SELECT Id, Name, RecordTypeId, Master_Account__c, Master_Client_Account__c FROM Relationship__c WHERE RecordTypeId = :CONTRACT_PARTNERSHIP_RT_ID];
        for (Relationship__c rel : relationships) {
            rel.Master_Account__c = partnerAccount.Id;
        }
        
        update relationships;

        Test.startTest();

        List<Relationship__c> rels  = RelatedClientAccountsCtrl.getRelatedClientAccounts(partnerAccount.Id);

        Test.stopTest();
		
        //Should be multiple Relationships created
        System.assertNotEquals(0, rels.size());
        for (Relationship__c rel : rels) {
            //Each Relationship should be associated with the Partner Account
            System.assertEquals(partnerAccount.Id, rel.Master_Account__c);
            //Each Relationship should have the Contract Partnership Record Type
            System.assertEquals(CONTRACT_PARTNERSHIP_RT_ID, rel.RecordTypeId);
        }
    }

    @isTest
    static void getRelatedClientAccountsRelationshipsNotLinkedToPartnerAccountTest() {
        Account partnerAccount = getPartnerAccount();

        Test.startTest();
        
        List<Relationship__c> rels = RelatedClientAccountsCtrl.getRelatedClientAccounts(partnerAccount.Id);

        Test.stopTest();

        //No Relationships should be returned as they were never associated with a Partner Account
        System.assertEquals(0, rels.size());
    }
}