src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Activated_Percent_HTN__c</fullName>
        <description>Member Activation percentage (for Hypertension)</description>
        <label>Activated Percent (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Activation__c</fullName>
        <description>Member Activation percent (for Diabetes)</description>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Activated Percent (Diabetes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Client_Risk_Notes__c</fullName>
        <description>Place to track details regarding the Account Health Score (green, yellow, red) and possible risks to the account health</description>
        <label>Account Health Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Coverage_Percentage_DM__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Email Coverage Percentage (DM)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Email_Coverage_Percentage_HTN__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Email Coverage Percentage (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Enrollment_Percentage_rPwDs__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Enrollment Percentage (rPwDs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Enrollment_Percentage_rPwHs__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Enrollment Percentage (rPwHs)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Usage_Last_30_day_Diabetes__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Usage % Last 30 day (Diabetes)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Usage_Last_30_day_HTN__c</fullName>
        <inlineHelpText>Updated by Sales Ops. If you see a problem, please contact SalesOps@livongo.com</inlineHelpText>
        <label>Usage % Last 30 day (HTN)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <recordTypes>
        <fullName>Client_Account</fullName>
        <active>true</active>
        <description>Sales account associated with direct-client relationships (e.g. employer groups)</description>
        <label>Client Account</label>
    </recordTypes>
    <recordTypes>
        <fullName>Partner_Account</fullName>
        <active>true</active>
        <description>Non-sales account associated with partner relationships (e.g. Health Plans, PBMs, Benefit Consultants)</description>
        <label>Partner Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AccountTriggerHandler.cls
/**
* AccountTriggerHandler Class
* 
*/

public class AccountTriggerHandler {
    public static final Id CLIENT_ACCOUNT_RT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Client_Account').getRecordTypeId();
    public static final Id PARTNER_ACCOUNT_RT = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Partner_Account').getRecordTypeId();
    
    public static void handleAccountUpdate(Map<Id,Account> oldAccounts, List<Account> newAccounts) {
        List<Account> updatedAccounts = new List<Account>();
        List<Account> hsUpdateAccounts = new List<Account>();
        List<Account> hsProgramScoreAccounts = new List<Account>();
        for(Account acc : newAccounts){
            if(acc.Client_Risk_Notes__c != null && acc.Client_Risk_Notes__c != oldAccounts.get(acc.Id).Client_Risk_Notes__c){
                updatedAccounts.add(acc);
            }
            if ((acc.RecordTypeId == CLIENT_ACCOUNT_RT || acc.RecordTypeId == CLIENT_ACCOUNT_RT) &&
                acc.Enrollment_Percentage_rPwDs__c != null && acc.Enrollment_Percentage_rPwDs__c != oldAccounts.get(acc.Id).Enrollment_Percentage_rPwDs__c ||
                acc.Enrollment_Percentage_rPwHs__c != null && acc.Enrollment_Percentage_rPwHs__c != oldAccounts.get(acc.Id).Enrollment_Percentage_rPwHs__c || 
                acc.Activation__c  != null && acc.Activation__c  != oldAccounts.get(acc.Id).Activation__c || 
                acc.Activated_Percent_HTN__c != null && acc.Activated_Percent_HTN__c != oldAccounts.get(acc.Id).Activated_Percent_HTN__c ||
                acc.Usage_Last_30_day_Diabetes__c != null && acc.Usage_Last_30_day_Diabetes__c != oldAccounts.get(acc.Id).Usage_Last_30_day_Diabetes__c ||
                acc.Usage_Last_30_day_HTN__c != null && acc.Usage_Last_30_day_HTN__c != oldAccounts.get(acc.Id).Usage_Last_30_day_HTN__c ||
                acc.Email_Coverage_Percentage_DM__c != null && acc.Email_Coverage_Percentage_DM__c != oldAccounts.get(acc.Id).Email_Coverage_Percentage_DM__c || 
                acc.Email_Coverage_Percentage_HTN__c != null && acc.Email_Coverage_Percentage_HTN__c != oldAccounts.get(acc.Id).Email_Coverage_Percentage_HTN__c) {
                    hsUpdateAccounts.add(acc);
                }
        }
        if (!updatedAccounts.isEmpty()) {
            AccountService.autoCreateNote(updatedAccounts);           
        }
        if (!hsUpdateAccounts.isEmpty()) {
            AccountService.updateHealthScores(hsUpdateAccounts, oldAccounts);
        }
    }
    public static void handleAccountAfterInsert(List<Account> newAccounts) {
        List<Account> accList = new List<Account>();
        for (Account acc: newAccounts) {
            if (acc.RecordTypeId == CLIENT_ACCOUNT_RT || acc.RecordTypeId == PARTNER_ACCOUNT_RT) {
                accList.add(acc);
            }
        }
        if (!accList.isEmpty()) {
            AccountService.createHealthScores(accList);
        }
    }
}