src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>CSM assigned to account</description>
        <label>Client Success Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_ARR__c</fullName>
        <description>JENGA-493</description>
        <inlineHelpText>Client BoB ARR(Across all programs)</inlineHelpText>
        <label>Client ARR</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>CSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Integrated with Redshift</description>
        <inlineHelpText>Integrated with Redshift</inlineHelpText>
        <label>Client Success Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Client_Overviews1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Path</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Contract Path)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Scores</relationshipLabel>
        <relationshipName>Health_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <label>Actual Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                    <isActive>false</isActive>
                    <label>Behavioral Health</label>
                </value>
                <value>
                    <fullName>Diabetes Prevention</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes Prevention</label>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                    <isActive>false</isActive>
                    <label>Weight Management</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Adjusted_Annual_Renewal_Value_Enrolled__c</fullName>
        <formula>IF 
( ISPICKVAL(Type,&quot;Renewal&quot;), 
(Livongo_for_Diabetes_PwDs__c * Livongo_for_Diabetes_PPPM__c *12) 
+ 
(Livongo_for_Hypertension_PwHs__c * Livongo_for_Hypertension_PPPM__c * 12)
+
(Livongo_DPP_PwPDs__c * Livongo_DPP_PPPM__c * 12) 
+ 
( Livongo_for_Weight_Management_DP_PwOs__c * Livongo_for_Weight_Management_DP_PPPM__c * 12), 
0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Adjusted Annual Renewal Value (Enrolled)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Success Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Direct contracts, please select &quot;Livongo&quot;. Indicates the Contract Path for the Opportunity, and required for Opps to be closed won. Once an Opp is won, the Contract Path will be represented as a relationship associated to the Client Overview.</description>
        <inlineHelpText>Direct contracts, please select &quot;Livongo&quot;. Indicates the Contract Path for the Opportunity, and required for Opps to be closed won. Once an Opp is won, the Contract Path will be represented as a relationship associated to the Client Overview.</inlineHelpText>
        <label>Contract Path</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Path must be a Partner Account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <infoMessage>Contract Path must be a Partner Account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Contract Path)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gross_ARR__c</fullName>
        <label>Gross ARR</label>
        <summarizedField>OpportunityLineItem.Gross_Program_ARR_Copy__c</summarizedField>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Livongo_for_Diabetes_PPPM__c</fullName>
        <label>Livongo for Diabetes PPPM</label>
        <summarizedField>OpportunityLineItem.UnitPrice</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.OpportunityProductName__c</field>
            <operation>equals</operation>
            <value>Livongo for Diabetes</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Livongo_for_Diabetes_PwDs__c</fullName>
        <label>Livongo for Diabetes PwDs</label>
        <summarizedField>OpportunityLineItem.Product_Participants__c</summarizedField>
        <summaryFilterItems>
            <field>OpportunityLineItem.OpportunityProductName__c</field>
            <operation>equals</operation>
            <value>Livongo for Diabetes, DM Solution</value>
        </summaryFilterItems>
        <summaryForeignKey>OpportunityLineItem.OpportunityId</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Original_Contract__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This field is related only to Contract Path Change opportunities and is required for commissions to be tied between the original sale, the original contract, and the updated contract via a new path.</description>
        <inlineHelpText>This field is related only to Contract Path Change opportunities and is required for commissions to be tied between the original sale, the original contract, and the updated contract via a new path.</inlineHelpText>
        <label>Original Contract</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You can only associate Client Overview records to this Opportunity.</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Opportunities (Original Contract)</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Gross_Program_ARR_Copy__c</fullName>
        <label>Gross Program ARR Copy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Program_ARR__c</fullName>
        <formula>CASE(
    Program_Family__c,

    &apos;Diabetes&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.25 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                (0.20 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),
    
    &apos;Hypertension&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                    (0.08 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),

    &apos;Weight Management&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
                         IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
                         IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), 0.10 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                         0.08 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12))),
    
    &apos;Prediabetes&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
                    IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
                    IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), 0.10 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                    0.08 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c* Incremental_Sales_Price__c * 12))),

    Product_Participants__c * UnitPrice * 12 + Product_Participants__c * 0.02 * PMPM__c * 6
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Program ARR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityProductName__c</fullName>
        <label>Opportunity Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pricing_Structure__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
        <label>Pricing Structure</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Pricing Structure is not available.</errorMessage>
            <filterItems>
                <field>Pricing_Structure__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program_ID__c</valueField>
            </filterItems>
            <filterItems>
                <field>Pricing_Structure__c.Price_Book__c</field>
                <operation>equals</operation>
                <valueField>$Source.Price_Book_ID__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pricing_Structure__c</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Participants__c</fullName>
        <inlineHelpText>For new opportunities, enter estimated recruitables or rPwX. For renewals, enter enrolled members.</inlineHelpText>
        <label>Program Participants (rPwX or Enrolled)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Family__c</fullName>
        <formula>TEXT(PricebookEntry.Product2.Family)</formula>
        <label>Program Family</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/objects/Pricing_Structure__c.object
<CustomObject>
    <fields>
        <fullName>Program__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Price_Book_Entry_Variations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityTriggerTest.cls
@isTest
public class OpportunityTriggerTest {
    public static final String NEW_BUSINESS = 'New Business';
    public static final String RENEWAL = 'Renewal';
    public static final String EXPANSION = 'Expansion';
    public static final String CROSSSELL = 'Cross-sell (New product)';
    public static final String CONTRACTPATHCHANGE = 'Contract Path Change';
    @TestSetup
    static void setupData() {
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        
        Account partnerAccount = TestFactory.createPartnerAccount();
        insert partnerAccount;
        
        Contract clientOverview = TestFactory.createClientOverview();
        clientOverview.AccountId = clientAccount.Id;
        clientOverview.Contract_Path__c = partnerAccount.Id;
        clientOverview.CSM__c = System.UserInfo.getUserId();
        insert clientOverview;
        
        List<Opportunity> oppList = new List<Opportunity>();
        oppList.add(TestFactory.createTypeBasedOpportunity(NEW_BUSINESS));
        oppList.add(TestFactory.createTypeBasedOpportunity(RENEWAL));
        oppList.add(TestFactory.createTypeBasedOpportunity(EXPANSION));
        oppList.add(TestFactory.createTypeBasedOpportunity(CROSSSELL));
        oppList.add(TestFactory.createTypeBasedOpportunity(CONTRACTPATHCHANGE));
        
        for(Opportunity opp: oppList) {
            opp.AccountId = clientAccount.Id;
            opp.Contract_Path__c = partnerAccount.Id;
            if(opp.Type == CONTRACTPATHCHANGE) {
                opp.Original_Contract__c = clientOverview.Id;
            }
        }
        
        if(oppList.size() > 0) {
            insert oppList;
        }
        
        Pricebook2 livongoPricebook = TestFactory.createPricebook();
        insert livongoPricebook;
        
        List<Product2> programsList = new List<Product2>();
        programsList.add(TestFactory.createProgram('Livongo for Diabetes'));
        programsList.add(TestFactory.createProgram('Livongo for Hypertension'));
        programsList.add(TestFactory.createProgram('Livongo Diabetes Prevention Program'));
        
        insert programsList;
        
        Id standardPBId = Test.getStandardPricebookId();
        
        List<PricebookEntry> entriesList = new List<PricebookEntry>();
        List<PricebookEntry> livongoPBEntriesList = new List<PricebookEntry>();
        List<Pricing_Structure__c> pricingStructureList = new List<Pricing_Structure__c>();
        
        for(Product2 program: programsList) {
            entriesList.add(TestFactory.createPricebookEntry(standardPBId, program.Id));
            livongoPBEntriesList.add(TestFactory.createPricebookEntry(livongoPricebook.Id, program.Id));
            pricingStructureList.add(TestFactory.createPricingStructure(livongoPricebook.Id, program.Id));
        }
        
        insert entriesList;
        insert livongoPBEntriesList;
        insert pricingStructureList;
        
        Map<Id,Id> standardPricingStructureMap = new Map<Id,Id>();
        for(Pricing_Structure__c ps: pricingStructureList) {
            standardPricingStructureMap.put(ps.Program__c, ps.Id);
        }
        
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        
        for (Opportunity oppty: oppList) {
            for(PricebookEntry pbe: livongoPBEntriesList) {
                oliList.add(TestFactory.createOpportunityLineItem(oppty.Id, pbe.Id));
            }
        }
        
        insert oliList;
        
        for(OpportunityLineItem oli: oliList) {
            oli.Product_Participants__c = 100;
            oli.UnitPrice = 62.00;
            oli.OpportunityProductName__c = 'Livongo for Diabetes';
        }
        
        update oliList;
    }
    
    private static Account getAccountById(Id accId) {
        return [SELECT Id, Name, Client_ARR__c FROM Account WHERE Id = :accId LIMIT 1];
    }
    
    private static Set<Id> getAccountIdSet() {
        Map<Id, Account> accIdMap = new Map<Id, Account>([SELECT Id FROM Account LIMIT 200]);
        Set<Id> accIdSet = new Set<Id>(accIdMap.keySet());
        return accIdSet;
    }
    
    private static Opportunity getOpportunityByType(String Type) {
        return [SELECT Id, Name, AccountId, Type, Gross_ARR__c, Adjusted_Annual_Renewal_Value_Enrolled__c,
                Livongo_for_Diabetes_PPPM__c, Livongo_for_Diabetes_PwDs__c, Account.Client_Arr__c, CloseDate, 
                (SELECT Id, Product_Participants__c, UnitPrice, Pricing_Structure__r.Name, Quantity, Program_Family__c, 
                 Gross_Program_ARR__c, Gross_Program_ARR_Copy__c FROM OpportunityLineItems)
                FROM Opportunity WHERE Type = :Type LIMIT 1];
    }
    
    private static PricebookEntry getPBE() {
        return [SELECT Id FROM PricebookEntry WHERE Product2.Name = 'Livongo for Diabetes' AND Pricebook2.Name = 'Livongo' LIMIT 1];
    }
    
    private static List<OpportunityLineItem> getOLI() {
        return [SELECT Id, Name, Product_Participants__c,OpportunityProductName__c, UnitPrice, Pricing_Structure__r.Name, Quantity, Program_Family__c, Gross_Program_ARR__c, 
                Gross_Program_ARR_Copy__c FROM OpportunityLineItem]; 
    }
    
    @isTest
    static void singleNBOpportunityTest() {
        Opportunity opp = getOpportunityByType(NEW_BUSINESS);
        opp.StageName = 'Closed Won';
        
        Test.startTest();
        update opp;
        Test.stopTest();
        
        Account acc = getAccountById(opp.AccountId);
        
        System.assertEquals(opp.Gross_ARR__c , acc.Client_Arr__c);
    }
    
    @isTest
    static void singleRenewalOpportunityTest() {
        Opportunity opp = getOpportunityByType(RENEWAL);
        opp.StageName = 'Closed Won';
        
        Test.startTest();
        update opp;
        Test.stopTest();
        
        Account acc = getAccountById(opp.AccountId);
        
        System.assertEquals(opp.Adjusted_Annual_Renewal_Value_Enrolled__c , acc.Client_Arr__c);
    }
    
    @isTest
    static void newBusinessAndRenewalOpportunityTest() {
        Opportunity nbOpp = getOpportunityByType(NEW_BUSINESS);
        nbOpp.StageName = 'Closed Won';
        Opportunity renewalOpp = getOpportunityByType(RENEWAL);
        renewalOpp.StageName = 'Closed Won';
        
        Test.startTest();
        update nbOpp;
        update renewalOpp; 
        Test.stopTest();
        
        Account acc = getAccountById(renewalOpp.AccountId);
        
        System.assertEquals(renewalOpp.Adjusted_Annual_Renewal_Value_Enrolled__c , acc.Client_Arr__c);
    }
    
    @isTest
    static void renewalAndContractPathChangeOpportunityTest() {
        Opportunity renewalOpp = getOpportunityByType(RENEWAL);
        renewalOpp.StageName = 'Closed Won';

        Opportunity contractPathChangeOpp = getOpportunityByType(CONTRACTPATHCHANGE);
        contractPathChangeOpp.StageName = 'Closed Won';
        contractPathChangeOpp.CloseDate = Date.today().addDays(-1);
        
        Test.startTest();
        update renewalOpp; 
        update contractPathChangeOpp;
        Test.stopTest();
        
        Account acc = getAccountById(renewalOpp.AccountId);
        
        System.assertEquals(renewalOpp.Adjusted_Annual_Renewal_Value_Enrolled__c , acc.Client_Arr__c);
    }
    
    @isTest
    static void renewalAndContractPathChangeOpportunityTest2() {
        Opportunity renewalOpp = getOpportunityByType(RENEWAL);
        renewalOpp.StageName = 'Closed Won';
        renewalOpp.CloseDate = Date.today().addDays(-1);

        Opportunity contractPathChangeOpp = getOpportunityByType(CONTRACTPATHCHANGE);
        contractPathChangeOpp.StageName = 'Closed Won';
        
        Test.startTest();
        update renewalOpp; 
        update contractPathChangeOpp;
        Test.stopTest();
        
        Account acc = getAccountById(contractPathChangeOpp.AccountId);
        
        System.assertEquals(contractPathChangeOpp.Gross_ARR__c , acc.Client_Arr__c);
    }
    
    @isTest
    static void renewalAndExpansionOpportunityTest() {
        Opportunity renewalOpp = getOpportunityByType(RENEWAL);
        renewalOpp.StageName = 'Closed Won';
        renewalOpp.CloseDate = Date.today().addDays(-1);

        Opportunity expansionOpp = getOpportunityByType(EXPANSION);
        expansionOpp.StageName = 'Closed Won';
        
        Test.startTest();
        update renewalOpp; 
        update expansionOpp;
        Test.stopTest();
        
        Account acc = getAccountById(expansionOpp.AccountId);
        
        System.assertEquals(expansionOpp.Gross_ARR__c + renewalOpp.Adjusted_Annual_Renewal_Value_Enrolled__c, acc.Client_Arr__c);
    }
    
    @isTest
    static void renewalAndExpansionOpportunityTest2() {
        Opportunity renewalOpp = getOpportunityByType(RENEWAL);
        renewalOpp.StageName = 'Closed Won';

        Opportunity expansionOpp = getOpportunityByType(EXPANSION);
        expansionOpp.StageName = 'Closed Won';
        expansionOpp.CloseDate = Date.today().addDays(-1);
        
        PricebookEntry pbe = getPBE();
        OpportunityLineItem oli = TestFactory.createOpportunityLineItem(expansionOpp.Id, pbe.Id);
        insert oli;
        
        Test.startTest();
        update renewalOpp; 
        update expansionOpp;
        Boolean isProdutsMatched = OpportunityService.findIfOppProductsMatch(renewalOpp, expansionOpp);
        Test.stopTest();
        
        Account acc = getAccountById(expansionOpp.AccountId);
        
        System.assertEquals(isProdutsMatched, false);
        //System.assertEquals(expansionOpp.Gross_ARR__c + renewalOpp.Adjusted_Annual_Renewal_Value_Enrolled__c, acc.Client_Arr__c);
    }
    
    @isTest
    static void newBusinessAndContractPathChangeOpportunityTest() {
        Opportunity nbOpp = getOpportunityByType(NEW_BUSINESS);
        nbOpp.StageName = 'Closed Won';
        nbOpp.CloseDate = Date.today().addDays(-1);
        
        Opportunity contractPathChangeOpp = getOpportunityByType(CONTRACTPATHCHANGE);
        contractPathChangeOpp.StageName = 'Closed Won';
        
        Test.startTest();
        update nbOpp;
        update contractPathChangeOpp; 
        Test.stopTest();
        
        Account acc = getAccountById(contractPathChangeOpp.AccountId);
        
        System.assertEquals(contractPathChangeOpp.Gross_ARR__c , acc.Client_Arr__c);
    }
    
    @isTest
    static void newBusinessAndExpansionOpportunityTest() {
        Opportunity nbOpp = getOpportunityByType(NEW_BUSINESS);
        nbOpp.StageName = 'Closed Won';
        
        Opportunity expansionOpp = getOpportunityByType(EXPANSION);
        expansionOpp.StageName = 'Closed Won';
        
        Test.startTest();
        update nbOpp;
        update expansionOpp; 
        Test.stopTest();
        
        Account acc = getAccountById(expansionOpp.AccountId);
        
        System.assertEquals(nbOpp.Gross_ARR__c + expansionOpp.Gross_ARR__c, acc.Client_Arr__c);
    }
    
    @isTest
    static void clientARRUpdateFromAccountTest(){
        Set<Id> accIdSet = getAccountIdSet();
        
        Opportunity nbOpp = getOpportunityByType(NEW_BUSINESS);
        nbOpp.StageName = 'Closed Won';
        
        Opportunity expansionOpp = getOpportunityByType(EXPANSION);
        expansionOpp.StageName = 'Closed Won';

        Test.startTest();
        update nbOpp;
        update expansionOpp; 
        OpportunityService.handleClientARRUpdateFromAccount(accIdSet);
        Test.stopTest();
        
        Account acc = getAccountById(expansionOpp.AccountId);
        
        System.assertEquals(nbOpp.Gross_ARR__c + expansionOpp.Gross_ARR__c, acc.Client_Arr__c);
    }
    
    @isTest
    static void healthScoresTest() {
        Opportunity opp = getOpportunityByType(RENEWAL);
        opp.CloseDate = Date.today().addMonths(24);
        
        Test.startTest();
        update opp;
        Test.stopTest();
        
        List<Health_Score__c> hsList = [SELECT Id, Account__c, Actual_Result__c FROM Health_Score__c 
                                            WHERE Account__c = :opp.AccountId AND RecordType.Name = 'Account Health Score' 
                                            AND Health_Segment__c = 'Renewal Timing'];
        Health_Score__c hsScore = hsList[0];
        
        System.assertEquals('>1 year', hsScore.Actual_Result__c);
    }
}