src/objects/Account.object
<CustomObject>
    <recordTypes>
        <fullName>Marketing</fullName>
        <active>false</active>
        <label>Marketing</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Scores</relationshipLabel>
        <relationshipName>Health_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <label>Actual Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Business_Health__c</fullName>
        <label>Client Business Health</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Growing</fullName>
                </value>
                <value>
                    <fullName>Stable</fullName>
                </value>
                <value>
                    <fullName>Declining</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_NPS__c</fullName>
        <label>Client NPS</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Competitor_w_in_account__c</fullName>
        <label>Competitor w/in account</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Path_Status__c</fullName>
        <label>Contract Path Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Green Partner</fullName>
                </value>
                <value>
                    <fullName>Yellow Partner</fullName>
                </value>
                <value>
                    <fullName>Red/Black Partner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cross_Sells_Expansions__c</fullName>
        <label>Cross Sells/Expansions</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Expansion/cross sell opp/no additional programs to sell</fullName>
                </value>
                <value>
                    <fullName>On path to discussion</fullName>
                </value>
                <value>
                    <fullName>Partnership does not allow expansion</fullName>
                </value>
                <value>
                    <fullName>Client declined discussion</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Diastolic_BP_Reduction__c</fullName>
        <label>Diastolic BP Reduction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Executive_Sponsor_Interaction_Engagement__c</fullName>
        <label>Executive Sponsor Interaction/Engagement</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Seat at executive sponsor table</fullName>
                </value>
                <value>
                    <fullName>Livongo executive relationship</fullName>
                </value>
                <value>
                    <fullName>Client Advisory Board</fullName>
                </value>
                <value>
                    <fullName>Operational engagement</fullName>
                </value>
                <value>
                    <fullName>Reference/case study/white paper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Segment__c</fullName>
        <label>Health Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Active 30</fullName>
                </value>
                <value>
                    <fullName>Marketing Type (Outreach Stratification)</fullName>
                </value>
                <value>
                    <fullName>Email Coverage</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                </value>
                <value>
                    <fullName>eHba1c Reduction</fullName>
                </value>
                <value>
                    <fullName>ROI Status</fullName>
                </value>
                <value>
                    <fullName>Client Launch Date</fullName>
                </value>
                <value>
                    <fullName>Systolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Diastolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Program Score</fullName>
                </value>
                <value>
                    <fullName>Renewal Timing</fullName>
                </value>
                <value>
                    <fullName>Cross Sells/Expansions</fullName>
                </value>
                <value>
                    <fullName>Client NPS</fullName>
                </value>
                <value>
                    <fullName>Interaction Cadence</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor Interaction/Engagement</fullName>
                </value>
                <value>
                    <fullName>Contract Path/Partner Relationship/Status</fullName>
                </value>
                <value>
                    <fullName>Client Business Health</fullName>
                </value>
                <value>
                    <fullName>Issues</fullName>
                </value>
                <value>
                    <fullName>Competitor w/in account</fullName>
                </value>
                <value>
                    <fullName>Immediate Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Immediate_Action_Needed__c</fullName>
        <label>Immediate Action Needed</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Merger</fullName>
                </value>
                <value>
                    <fullName>Breach of Contract</fullName>
                </value>
                <value>
                    <fullName>Other Nuclear Issue</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interaction_Cadence__c</fullName>
        <label>Interaction Cadence</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Meeting established cadence</fullName>
                </value>
                <value>
                    <fullName>No meeting cadence/consistently cancels</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Issues__c</fullName>
        <label>Issues</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Marketing Issues</fullName>
                </value>
                <value>
                    <fullName>Data Issues</fullName>
                </value>
                <value>
                    <fullName>Billing Issues</fullName>
                </value>
                <value>
                    <fullName>Eligibility Issues</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Satisfaction__c</fullName>
        <label>Member Satisfaction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Participating_in_any_optimized_campaigns__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Participating in any optimized campaigns</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Population_Refresh__c</fullName>
        <label>Population Refresh</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>within 3 months</fullName>
                </value>
                <value>
                    <fullName>&gt; 3 months ago</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                    <isActive>false</isActive>
                    <label>Behavioral Health</label>
                </value>
                <value>
                    <fullName>Diabetes Prevention</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes Prevention</label>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                    <isActive>false</isActive>
                    <label>Weight Management</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROI_Status_DM__c</fullName>
        <label>ROI Status - DM</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client &lt;1.25 years on program or partnership doesn&apos;t allow ROI</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 with 100 activated, claims based completed</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 with 100 activated, fitch mode or BOB</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 years with no ROI completed</fullName>
                </value>
                <value>
                    <fullName>Client ROI completed but results were negative</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ROI_Status_HTN__c</fullName>
        <label>ROI Status - HTN</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Client &lt;1.25 years on program or partnership doesn&apos;t allow ROI</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 with 100 activated, claims based completed</fullName>
                </value>
                <value>
                    <fullName>Client &gt;1.25 years with no ROI completed</fullName>
                </value>
                <value>
                    <fullName>Client &gt; 1.25 years with ROI completed but negative results</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Systolic_BP_Reduction__c</fullName>
        <label>Systolic BP Reduction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>eHba1c_Reduction__c</fullName>
        <label>eHba1c Reduction</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <recordTypes>
        <fullName>Account_Health_Score</fullName>
        <active>true</active>
        <label>Account Health Score</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program_Health_Score</fullName>
        <active>true</active>
        <label>Program Health Score</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HealthScoreTriggerTest.cls
@isTest
public class HealthScoreTriggerTest {
    public static final Id ACCOUNT_HEALTH_SCORE_RT = Schema.SObjectType.Health_Score__c.getRecordTypeInfosByDeveloperName().get('Account_Health_Score').getRecordTypeId();
    public static final Id PROGRAM_HEALTH_SCORE_RT = Schema.SObjectType.Health_Score__c.getRecordTypeInfosByDeveloperName().get('Program_Health_Score').getRecordTypeId();
    
    @TestSetup
    static void setupData() {
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
    }
    
    private static Account getAccount() {
        return [SELECT Id FROM Account LIMIT 1];
    }
    
    private static List<Health_Score__c> getHealthScores(Id accId) {
        return [SELECT Id, Actual_Result__c, Health_Segment__c, Program__c, Cross_Sells_Expansions__c, RecordTypeId, 
                Client_NPS__c, Client_Business_Health__c, Interaction_Cadence__c, Executive_Sponsor_Interaction_Engagement__c,
                Contract_Path_Status__c, Issues__c, Competitor_w_in_account__c, Immediate_Action_Needed__c, Member_Satisfaction__c, 
                Participating_in_any_optimized_campaigns__c, Population_Refresh__c, eHba1c_Reduction__c, ROI_Status_DM__c, Systolic_BP_Reduction__c, 
                Diastolic_BP_Reduction__c, ROI_Status_HTN__c FROM Health_Score__c WHERE Account__c = :accId];
    }
    
    @isTest
    static void healthScoreUpdateTest1() {
        Account acc = getAccount();
        List<Health_Score__c> hsList = getHealthScores(acc.Id);
        for (Health_Score__c hs : hsList) {
            if (hs.RecordTypeId == ACCOUNT_HEALTH_SCORE_RT) {
                switch on hs.Health_Segment__c {
                    when 'Program Score' {
                        hs.Actual_Result__c = '80';
                    }
                    when 'Renewal Timing' {
                        hs.Actual_Result__c = '>1 year';
                    }
                    when 'Cross Sells/Expansions'{
                        hs.Cross_Sells_Expansions__c = 'Expansion/cross sell opp/no additional programs to sell';
                    }
                    when 'Client NPS' {
                        hs.Client_NPS__c = 60;
                    }
                    when 'Client Business Health' {
                        hs.Client_Business_Health__c = 'Growing';
                    }
                    when 'Interaction Cadence' {
                        hs.Interaction_Cadence__c = 'Meeting established cadence';
                    }
                    when 'Executive Sponsor Interaction/Engagement' {
                        hs.Executive_Sponsor_Interaction_Engagement__c = 'Seat at executive sponsor table';
                    }
                    when 'Contract Path/Partner Relationship/Status' {
                        hs.Contract_Path_Status__c = 'Green Partner';
                    }
                    when 'Issues' {
                        hs.Issues__c = 'Marketing Issues';
                    }
                    when 'Competitor w/in account' {
                        hs.Competitor_w_in_account__c = 'Yes';
                    }
                    when 'Immediate Action Needed' {
                        hs.Immediate_Action_Needed__c = 'Merger';
                    }
                }
            }
            else if (hs.RecordTypeId == PROGRAM_HEALTH_SCORE_RT) {
                if (hs.Program__c == 'Diabetes') {
                    switch on hs.Health_Segment__c {
                        when 'Member Satisfaction' {
                            hs.Member_Satisfaction__c = 75;
                        }
                        when 'Enrollment' {
                            hs.Actual_Result__c = '40';
                        }
                        when 'Activation' {
                            hs.Actual_Result__c = '80';
                        }
                        when 'Active 30' {
                            hs.Actual_Result__c = '90';
                        }
                        when 'Marketing Type (Outreach Stratification)' {
                            hs.Actual_Result__c = 'A';
                            hs.Participating_in_any_optimized_campaigns__c = true;
                        }
                        when 'Email Coverage' {
                            hs.Actual_Result__c = '50';
                        }
                        when 'Population Refresh' {
                            hs.Population_Refresh__c = 'within 3 months';
                        }
                        when 'eHba1c Reduction' {
                            hs.eHba1c_Reduction__c = 0.6;
                        }
                        when 'ROI Status' {
                            hs.ROI_Status_DM__c = 'Client <1.25 years on program or partnership doesn\'t allow ROI';
                        }
                    }
                }
                else if (hs.Program__c == 'Hypertension') {
                    switch on hs.Health_Segment__c {
                        when 'Member Satisfaction' {
                            hs.Member_Satisfaction__c = 80;
                        }
                        when 'Enrollment' {
                            hs.Actual_Result__c = '30';
                        }
                        when 'Activation' {
                            hs.Actual_Result__c = '75';
                        }
                        when 'Active 30' {
                            hs.Actual_Result__c = '80';
                        }
                        when 'Marketing Type (Outreach Stratification)' {
                            hs.Actual_Result__c = 'A';
                            hs.Participating_in_any_optimized_campaigns__c = true;
                        }
                        when 'Email Coverage' {
                            hs.Actual_Result__c = '40';
                        }
                        when 'Population Refresh' {
                            hs.Population_Refresh__c = 'within 3 months';
                        }
                        when 'Systolic BP Reduction' {
                            hs.Systolic_BP_Reduction__c = 8;
                        }
                        when 'Diastolic BP Reduction' {
                            hs.Diastolic_BP_Reduction__c = 5;
                        }
                        when 'ROI Status' {
                            hs.ROI_Status_HTN__c = 'Client <1.25 years on program or partnership doesn\'t allow ROI';
                        }
                    }
                }
            }
        }
        Test.startTest();
        update hsList;
        Test.stopTest();
        for (Health_Score__c hs : hsList) {
            if (hs.RecordTypeId == ACCOUNT_HEALTH_SCORE_RT) {
                switch on hs.Health_Segment__c {
                    when 'Program Score' {
                        System.assertEquals('80', hs.Actual_Result__c);
                    }
                    when 'Renewal Timing' {
                        System.assertEquals('>1 year', hs.Actual_Result__c);
                    }
                }
            }
        }
    }
    
    @isTest
    static void healthScoreUpdateTest2() {
        Account acc = getAccount();
        List<Health_Score__c> hsList = getHealthScores(acc.Id);
        for (Health_Score__c hs : hsList) {
            if (hs.RecordTypeId == ACCOUNT_HEALTH_SCORE_RT) {
                switch on hs.Health_Segment__c {
                    when 'Program Score' {
                        hs.Actual_Result__c = '65';
                    }
                    when 'Renewal Timing' {
                        hs.Actual_Result__c = '6 months - 1 year';
                    }
                    when 'Cross Sells/Expansions'{
                        hs.Cross_Sells_Expansions__c = 'On path to discussion';
                    }
                    when 'Client NPS' {
                        hs.Client_NPS__c = 45;
                    }
                    when 'Client Business Health' {
                        hs.Client_Business_Health__c = 'Stable';
                    }
                    when 'Interaction Cadence' {
                        hs.Interaction_Cadence__c = 'No meeting cadence/consistently cancels';
                    }
                    when 'Executive Sponsor Interaction/Engagement' {
                        hs.Executive_Sponsor_Interaction_Engagement__c = 'Livongo executive relationship';
                    }
                    when 'Contract Path/Partner Relationship/Status' {
                        hs.Contract_Path_Status__c = 'Yellow partner';
                    }
                    when 'Issues' {
                        hs.Issues__c = 'Marketing Issues';
                    }
                    when 'Competitor w/in account' {
                        hs.Competitor_w_in_account__c = 'No';
                    }
                    when 'Immediate Action Needed' {
                        hs.Immediate_Action_Needed__c = 'Merger';
                    }
                }
            }
            else if (hs.RecordTypeId == PROGRAM_HEALTH_SCORE_RT) {
                if (hs.Program__c == 'Diabetes') {
                    switch on hs.Health_Segment__c {
                        when 'Member Satisfaction' {
                            hs.Member_Satisfaction__c = 45;
                        }
                        when 'Enrollment' {
                            hs.Actual_Result__c = '25';
                        }
                        when 'Activation' {
                            hs.Actual_Result__c = '68';
                        }
                        when 'Active 30' {
                            hs.Actual_Result__c = '68';
                        }
                        when 'Marketing Type (Outreach Stratification)' {
                            hs.Actual_Result__c = 'B';
                            hs.Participating_in_any_optimized_campaigns__c = true;
                        }
                        when 'Email Coverage' {
                            hs.Actual_Result__c = '25';
                        }
                        when 'Population Refresh' {
                            hs.Population_Refresh__c = '> 3 months ago';
                        }
                        when 'eHba1c Reduction' {
                            hs.eHba1c_Reduction__c = 0.4;
                        }
                        when 'ROI Status' {
                            hs.ROI_Status_DM__c = 'Client >1.25 with 100 activated, fitch mode or BOB';
                        }
                    }
                }
                else if (hs.Program__c == 'Hypertension') {
                    switch on hs.Health_Segment__c {
                        when 'Member Satisfaction' {
                            hs.Member_Satisfaction__c = 45;
                        }
                        when 'Enrollment' {
                            hs.Actual_Result__c = '15';
                        }
                        when 'Activation' {
                            hs.Actual_Result__c = '65';
                        }
                        when 'Active 30' {
                            hs.Actual_Result__c = '65';
                        }
                        when 'Marketing Type (Outreach Stratification)' {
                            hs.Actual_Result__c = 'B';
                            hs.Participating_in_any_optimized_campaigns__c = true;
                        }
                        when 'Email Coverage' {
                            hs.Actual_Result__c = '25';
                        }
                        when 'Population Refresh' {
                            hs.Population_Refresh__c = '> 3 months ago';
                        }
                        when 'Systolic BP Reduction' {
                            hs.Systolic_BP_Reduction__c = 4;
                        }
                        when 'Diastolic BP Reduction' {
                            hs.Diastolic_BP_Reduction__c = 4;
                        }
                        when 'ROI Status' {
                            hs.ROI_Status_HTN__c = 'Client >1.25 years with no ROI completed';
                        }
                    }
                }
            }
        }
        Test.startTest();
        update hsList;
        Test.stopTest();
        for (Health_Score__c hs : hsList) {
            if (hs.RecordTypeId == ACCOUNT_HEALTH_SCORE_RT) {
                switch on hs.Health_Segment__c {
                    when 'Program Score' {
                        System.assertEquals('65', hs.Actual_Result__c);
                    }
                    when 'Renewal Timing' {
                        System.assertEquals('6 months - 1 year', hs.Actual_Result__c);
                    }
                }
            }
        }
    }
}