src/objects/CHS_Contact_Roles__mdt.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>CHS Contact Roles</label>
    <pluralLabel>CHS Contact Roles</pluralLabel>
</CustomObject>

src/objects/Client_Handoff_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Handoff Summary</relationshipLabel>
        <relationshipName>Client_Handoff_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Handoff Summary</relationshipLabel>
        <relationshipName>Client_Handoff_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskRay_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Client Handoff Summary</relationshipLabel>
        <relationshipName>Client_Handoff_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Handoff Summary</label>
    <nameField>
        <displayFormat>CHS# {00000}</displayFormat>
        <label>Client Handoff Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Handoff Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Include_in_Client_Strategy_Calls_Emails__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Include in Client Strategy Calls/Emails?</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <description>Integrated with NetSuite and Redshift</description>
        <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Prediabetes</fullName>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClientHandoffSummaryController.cls
public with sharing class ClientHandoffSummaryController {
    public static List<CHS_Contact_Roles__mdt> accConRolesMDT {get; set;}
    static {
        CHS_Contact_Roles__mdt[] conRoles = [SELECT Role__c FROM CHS_Contact_Roles__mdt];
        accConRolesMDT = conRoles;
    }
    @AuraEnabled(cacheable=true)
    public static List<Contract> getPrograms(Id clientHandoffId){
        Client_Handoff_Summary__c clientHandoffSummary = getClientHandoffSummaryRecord(clientHandoffId);
        Id clientOverviewId = clientHandoffSummary.Client_Overview__c;
        List<Contract> contractList = [SELECT Id, Program_Name__c FROM Contract WHERE Client_Overview__c =: clientOverviewId];
        return contractList;
    }
    @AuraEnabled(cacheable=true)
    public static List<AccountContactRelation> getAccountContactRelationships(Id clientHandoffId) {
        String roleString = '';
        for(CHS_Contact_Roles__mdt crm: accConRolesMDT) {
            roleString += '\'' + crm.Role__c + '\',';
        }
        roleString = roleString.removeEnd(',');
        Client_Handoff_Summary__c clientHandoffSummary = getClientHandoffSummaryRecord(clientHandoffId);
        Id taskRayAccountId = clientHandoffSummary.Account__c;
        String queryString = 'SELECT Id, AccountId, ContactId, Account.Name, Contact.Name, Contact.Email, Contact.Phone, Contact.Description,'+ 
                                'Roles, Contact.Include_in_Client_Strategy_Calls_Emails__c, Contact.Title, Contact.Account.Name,'+
                                'Contact.FirstName, Contact.LastName FROM AccountContactRelation WHERE AccountId =: taskRayAccountId AND Roles includes (' + roleString +')';
        List<AccountContactRelation> accConRelList = Database.Query(queryString);
        return accConRelList;
    }
    private static Client_Handoff_Summary__c getClientHandoffSummaryRecord(Id chsId) {
        return [SELECT Id, TaskRay_Project__c, Client_Overview__c, Account__c
                 FROM Client_Handoff_Summary__c WHERE Id =: chsId LIMIT 1];
    }
}