src/objects/Client_Handoff_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Handoff Summary</relationshipLabel>
        <relationshipName>Client_Handoff_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskRay_Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TaskRay Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Client Handoff Summary</relationshipLabel>
        <relationshipName>Client_Handoff_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Handoff Summary</label>
    <nameField>
        <displayFormat>CHS# {00000}</displayFormat>
        <label>Client Handoff Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Handoff Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskRayProjectTriggerTest.cls
@isTest
public with sharing class TaskRayProjectTriggerTest {
    @TestSetup
    static void testData(){
        Account clientAccount = TestFactory.createClientAccount();
        Contract clientOverview = TestFactory.createClientOverview();
        insert clientAccount;

        clientOverview.AccountId = clientAccount.Id;
        insert clientOverview;
    }
    private static Contract getClientOverview() {
        return [SELECT Id, AccountId FROM Contract LIMIT 1];
    }
    @isTest
    static void createTaskRayProjectTest() {
        Contract co = getClientOverview();
        TASKRAY__Project__c  project = TestFactory.createTaskRayProject();
        insert project;

        project.Client_Overview__c = co.Id;

        Test.startTest();
        update project;
        Test.stopTest();
        
        List<Client_Handoff_Summary__c> chsList = [SELECT Id FROM Client_Handoff_Summary__c WHERE TaskRay_Project__c =: project.Id];
        System.assertEquals(1, chsList.size());
    }
}