src/objects/Client_Handoff_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Handoff Summary</relationshipLabel>
        <relationshipName>Client_Handoff_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Client Handoff Summary</relationshipLabel>
        <relationshipName>Client_Handoff_Summary</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Client Handoff Summary</label>
    <nameField>
        <displayFormat>CHS# {00000}</displayFormat>
        <label>Client Handoff Summary Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Handoff Summary</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <description>Integrated with NetSuite and Redshift</description>
        <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Prediabetes</fullName>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Program_Overview</fullName>
        <active>true</active>
        <description>Represents the program-specific, Program Schedule under a Program Agreement + the Client&apos;s specific operational processes regarding the program</description>
        <label>Program Overview</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>This junction object links Client with Partner Accounts, Partner Accounts with Client Opportunities, Client Accounts with Competitor Accounts, and Competitor Accounts with Client Opportunities.</description>
    <fields>
        <fullName>Client_Partnership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Client Account for linking to a Partner Account.</description>
        <inlineHelpText>Lookup to a Client Account for linking to a Partner Account.</inlineHelpText>
        <label>Client Account (P)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client-Level Partnerships</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Partnership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Contract in a relationship between a deal and Partner.</description>
        <inlineHelpText>The related Contract in a relationship between a deal and Partner.</inlineHelpText>
        <label>Contract (P)</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract-Level Partnerships (Contract)</relationshipLabel>
        <relationshipName>ContractRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Contract_Partnership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Partner Account for linking a Partner Account to a Contract.</description>
        <inlineHelpText>Lookup to a Partner Account for linking a Partner Account to a Contract.</inlineHelpText>
        <label>Partner Account (C)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract-Level Partnership (Partner)</relationshipLabel>
        <relationshipName>Relationships4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Partnership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Partner or Employer Account in a relationship between a Client and Partner or Employer Account.</description>
        <inlineHelpText>The Partner or Employer Account in a relationship between a Client and Partner or Employer Account.</inlineHelpText>
        <label>Partner Account (A)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client-Level Partnerships (Partner)</relationshipLabel>
        <relationshipName>RelatedAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipType__c</fullName>
        <description>Defines the type of relationship between two entities.</description>
        <inlineHelpText>Defines the type of relationship between two entities.</inlineHelpText>
        <label>Relationship Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Activity Tracking Devices</fullName>
                </value>
                <value>
                    <fullName>Associated Health Plan</fullName>
                </value>
                <value>
                    <fullName>Asthma</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Benefits Consultant</fullName>
                </value>
                <value>
                    <fullName>Billing Partner</fullName>
                </value>
                <value>
                    <fullName>Biometrics Screening/Health  Risk Assessment</fullName>
                </value>
                <value>
                    <fullName>Blue Cross Blue Shield Federal Employee Program</fullName>
                    <isActive>false</isActive>
                    <label>Blue Cross Blue Shield Federal Employee Program</label>
                </value>
                <value>
                    <fullName>Cardiovascular Health</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                </value>
                <value>
                    <fullName>Children&apos;s Health and Obesity</fullName>
                </value>
                <value>
                    <fullName>Cohort</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Concierge/Coaching Advocacy</fullName>
                </value>
                <value>
                    <fullName>Contract Path</fullName>
                </value>
                <value>
                    <fullName>Contract Terms</fullName>
                </value>
                <value>
                    <fullName>Cost Transparency</fullName>
                </value>
                <value>
                    <fullName>Data - Eligibility File</fullName>
                </value>
                <value>
                    <fullName>Data - Eligibility File - Historical</fullName>
                    <isActive>false</isActive>
                    <label>Data - Eligibility File - Historical</label>
                </value>
                <value>
                    <fullName>Data - Email</fullName>
                </value>
                <value>
                    <fullName>Data - Historical</fullName>
                    <isActive>false</isActive>
                    <label>Data - Historical</label>
                </value>
                <value>
                    <fullName>Data - Medical Claims</fullName>
                </value>
                <value>
                    <fullName>Data - N/A – No Livongo Marketing</fullName>
                </value>
                <value>
                    <fullName>Data - Other</fullName>
                </value>
                <value>
                    <fullName>Data - Pharmacy Claims</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List</fullName>
                    <isActive>false</isActive>
                    <label>Data - Predefined List</label>
                </value>
                <value>
                    <fullName>Data - Predefined List from Biometric</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from EMR</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from HRA</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from Medical Claims</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <recordTypes>
        <fullName>Account_Partnership</fullName>
        <active>true</active>
        <description>Partner at the Client Account level (Health Plan/Payer, Benefits Consultant, PBM, Wellness Coordinator, or Cohort)</description>
        <label>Account Partnership</label>
    </recordTypes>
    <recordTypes>
        <fullName>Contract_Partnership</fullName>
        <active>true</active>
        <description>Partner at the Contract level (Admin Party, Billing Partner, Care Coordinator, Contract Path, Contract Terms, or Data)</description>
        <label>Contract Partnership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClientHandoffSummaryControllerTest.cls
@isTest
public with sharing class ClientHandoffSummaryControllerTest {
    public static final Id PROGRAM_OVERVIEW_RT = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Program_Overview').getRecordTypeId();
    public static final Id ACCOUNT_PARTNERSHIP_RT = Schema.SObjectType.Relationship__c.getRecordTypeInfosByDeveloperName().get('Account_Partnership').getRecordTypeId();
    public static final Id CONTRACT_PARTNERSHIP_RT = Schema.SObjectType.Relationship__c.getRecordTypeInfosByDeveloperName().get('Contract_Partnership').getRecordTypeId();
    public static List<String> relationshipTypes = ClientHandoffSummaryPdfController.relationshipTypes;
    
    @TestSetup
    static void testData(){
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        
        Account partnerAccount = TestFactory.createPartnerAccount();
        insert partnerAccount;
                
        List<Contract> clist = new List<Contract>();
        Contract clientOverview = TestFactory.createClientOverview();
        clientOverview.AccountId = clientAccount.Id;
        clist.add(clientOverview);

        if(clist.size() > 0) {
            insert cList;
        }

        List<Contact> conList = new List<Contact>();
        for(integer i=0; i<3; i++) {
            Contact con = TestFactory.createSalesContact();
            con.AccountId = clientAccount.Id;
            conList.add(con);
        }
        insert conList;
        
        List<Opportunity> oppList = new List<Opportunity>();
        for(integer i=0; i<3; i++) {
            Opportunity opp = TestFactory.createTypeBasedOpportunity('New Business');
            opp.AccountId = clientAccount.Id;
            oppList.add(opp);
        }
        insert oppList;
        
        List<Relationship__c> relList = new List<Relationship__c>();
        for(integer i=0; i<3; i++) {
            Relationship__c rel = TestFactory.createRelationship('Benefits Consultant');
            rel.Client_Partnership__c = clientAccount.Id;
            rel.Partner_Partnership__c = partnerAccount.Id;
            rel.RecordTypeId = ACCOUNT_PARTNERSHIP_RT;
            relList.add(rel);
        }
        for(integer i=0; i<3; i++) {
            Relationship__c rel = TestFactory.createRelationship('Billing Partner');
            rel.Contract_Partnership__c = clientOverview.Id;
            rel.Partner_Contract_Partnership__c  = partnerAccount.Id;
            rel.RecordTypeId = CONTRACT_PARTNERSHIP_RT;
            relList.add(rel);
        }
        insert relList;

        Contract programOverview = TestFactory.createProgramOverview();
        Contract programOverview2 = TestFactory.createProgramOverview();
        Contract programOverview3 = TestFactory.createProgramOverview();

        programOverview.Client_Overview__c = clientOverview.Id;
        programOverview.AccountId = clientAccount.Id;
        programOverview.Program_Name__c = 'Diabetes';

        programOverview2.Client_Overview__c = clientOverview.Id;
        programOverview2.AccountId = clientAccount.Id;
        programOverview2.Program_Name__c = 'Hypertension';

        programOverview3.Client_Overview__c = clientOverview.Id;
        programOverview3.AccountId = clientAccount.Id;
        programOverview3.Program_Name__c = 'Prediabetes';

        cList.add(programOverview);
        cList.add(programOverview2);
        cList.add(programOverview3);

        if(clist.size() > 0) {
            upsert cList;
        }

        TASKRAY__Project__c  project = TestFactory.createTaskRayProject();
        project.Client_Overview__c = clientOverview.Id;
        insert project;

        Client_Handoff_Summary__c chs = TestFactory.createClientHandoffSummary();
        chs.Client_Overview__c = clientOverview.Id;
        chs.Account__c = clientAccount.Id;
        insert chs;
    }

    private static Client_Handoff_Summary__c getCHS() {
        return [SELECT Id, Client_Overview__c, Account__c FROM Client_Handoff_Summary__c LIMIT 1];
    }
    
    private static List<AccountContactRelation> getAccConRelList() {
        return [SELECT Id, AccountId, ContactId, Roles FROM AccountContactRelation];
    }
    
    private static List<Opportunity> getOpportunities() {
        return [SELECT Id FROM Opportunity];
    }
    
    private static List<Contract> getProgramOverviews() {
        return [SELECT Id FROM Contract WHERE RecordTypeId = :PROGRAM_OVERVIEW_RT];
    }
    
    private static List<Relationship__c> getAccountRelationships() {
       return [SELECT Id FROM Relationship__c WHERE RecordTypeId = :ACCOUNT_PARTNERSHIP_RT];
    }
    
    private static List<Relationship__c> getContractRelationships() {
       return [SELECT Id, RecordType.Name, RelationshipType__c FROM Relationship__c WHERE RecordTypeId = :CONTRACT_PARTNERSHIP_RT 
               AND RelationshipType__c IN :relationshipTypes];
    }
    	
    @isTest
    static void getProgramsTest() {
        Client_Handoff_Summary__c chs = getCHS();
        List<Contract> expectedprogramsList = getProgramOverviews();
        Test.startTest();
        List<Contract> programList = ClientHandoffSummaryController.getPrograms(chs.Id);
        Test.stopTest();
        System.assertEquals(expectedprogramsList.size(), programList.size());
    }

    @isTest
    static void getAccountContactRelationshipsTest() {
        Client_Handoff_Summary__c chs = getCHS();
        List<AccountContactRelation> accConRelList = getAccConRelList();
        for (AccountContactRelation accConRel: accConRelList) {
            accConRel.Roles = 'Billing POC;Executive Sponsor';
        }
        update accConRelList;
        Test.startTest();
        List<AccountContactRelation> accConRelListResult = ClientHandoffSummaryController.getAccountContactRelationships(chs.Id);
        Test.stopTest();
        System.assertEquals(getAccConRelList().size(), accConRelListResult.size());
    }
    
      
    @isTest
    static void clientHandoffSummaryPDFControllerTest() {
        Client_Handoff_Summary__c chs = getCHS();
        List<Opportunity> oppList = getOpportunities();
        List<Contract> programList = getProgramOverviews();
        List<AccountContactRelation> accConRelList = getAccConRelList();
        for (AccountContactRelation accConRel: accConRelList) {
            accConRel.Roles = 'Billing POC;Executive Sponsor';
        }
        update accConRelList;
        List<Relationship__c> accRelationships = getAccountRelationships();
        List<Relationship__c> contractRelationships = getContractRelationships();
        Test.startTest();
        ApexPages.currentPage().getParameters().put('id',String.valueOf(chs.Id));
        ClientHandoffSummaryPdfController.ClientHandoffSummaryWrapper  chsWrapper = new ClientHandoffSummaryPdfController.ClientHandoffSummaryWrapper();
        ClientHandoffSummaryPdfController chsPDFController = new ClientHandoffSummaryPdfController();
        chsWrapper=chsPDFController.theCHS;
        Test.stopTest();
        System.assertEquals(chs.Client_Overview__c, chsWrapper.clientHandoffSummary.Client_Overview__c);
        System.assertEquals(chs.Account__c, chsWrapper.clientHandoffSummary.Account__c);
        System.assertEquals(oppList.size(), chsWrapper.opportunitiesForParentAccount.size());
        System.assertEquals(programList.size(), chsWrapper.programOverviews.size());
        System.assertEquals(accConRelList.size(), chsWrapper.accountContactRelationships.size());
        System.assertEquals(accRelationships.size(), chsWrapper.partnerRelationshipForParentAccount.size());
        System.assertEquals(contractRelationships.size(), chsWrapper.contractPartnerRelationshipForParentAccount.size());
    }
}