src/objects/ClientMemberCode__c.object
<CustomObject>
    <description>Client Member Codes may be used to facilitate registration or to classify clients into groups for reporting and billing (or a combination of these options).  Legacy Registration Codes and Tags are captured as Client Member Codes in Salesforce.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Defines the relationship between a Client Account and a Client Member Code</description>
        <inlineHelpText>Defines the relationship between a Client Account and a Client Member Code</inlineHelpText>
        <label>Client Account</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must choose an Account with record type Client Account or Downmarket Client</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Account, Downmarket Client, Partner Account</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Client Member Codes</relationshipLabel>
        <relationshipName>Client_Member_Groups</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ClientMemberCode__c</fullName>
        <description>Defines the Client Member Code value (e.g. &quot;VALLEYPROTEINS&quot;)</description>
        <inlineHelpText>Defines the Client Member Code value (e.g. &quot;VALLEYPROTEINS&quot;).
The Client Member Code must contain only UPPERCASE letters, numbers, and/or a dash. It should not contain any other special characters</inlineHelpText>
        <label>Code</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Client Member Code</label>
    <nameField>
        <displayFormat>CMC-{000000}</displayFormat>
        <label>CM Code Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Member Codes</pluralLabel>
    <recordTypes>
        <fullName>ClientMemberCode</fullName>
        <active>true</active>
        <label>Client Member Code</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClientMemberCodeTest.cls
@isTest
public class ClientMemberCodeTest {
 
    @isTest(SeeAllData=true)
    static void insertClientMemberCode(){
        
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;        
        ClientMemberCode__c memberCode=TestFactory.createClientMemberCode();
        memberCode.Account__c=clientAccount.Id;
        Test.startTest();
       	insert memberCode;
       	Test.stopTest(); 
        String recordTypeId=Schema.SObjectType.ClientMemberCode__c.getRecordTypeInfosByDeveloperName().get('ClientMemberCode').getRecordTypeId();
        System.assertEquals(clientAccount.Id,memberCode.Account__c);
        System.assertEquals('CMCXYZ9000',membercode.ClientMemberCode__c);
        System.assertEquals(recordTypeId, membercode.RecordTypeId);  
    }
    
   
    @isTest(SeeAllData=true)
    static void deleteClientMemberCode(){
        
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;        
        ClientMemberCode__c memberCode=TestFactory.createClientMemberCode();
        memberCode.Account__c=clientAccount.Id;
        insert memberCode;
        Test.startTest();
        delete memberCode;
       	Test.stopTest();     
        String recordTypeId=Schema.SObjectType.ClientMemberCode__c.getRecordTypeInfosByDeveloperName().get('ClientMemberCode').getRecordTypeId();
        System.assertEquals(clientAccount.Id,memberCode.Account__c);
        System.assertEquals('CMCXYZ9000',membercode.ClientMemberCode__c);
        System.assertEquals(recordTypeId, membercode.RecordTypeId); 
        
    }
}