src/objects/ClientMemberCode__c.object
<CustomObject>
    <description>Client Member Codes may be used to facilitate registration or to classify clients into groups for reporting and billing (or a combination of these options).  Legacy Registration Codes and Tags are captured as Client Member Codes in Salesforce.</description>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientMemberCode__c</fullName>
        <description>Defines the Client Member Code value (e.g. &quot;VALLEYPROTEINS&quot;)</description>
        <inlineHelpText>Defines the Client Member Code value (e.g. &quot;VALLEYPROTEINS&quot;).
The Client Member Code must contain only UPPERCASE letters, numbers, and/or a dash. It should not contain any other special characters</inlineHelpText>
        <label>Code</label>
        <length>32</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Client Member Code</label>
    <nameField>
        <displayFormat>CMC-{000000}</displayFormat>
        <label>CM Code Assignment Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Client Member Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClientMemberCodeService.cls
public class ClientMemberCodeService {
    public static void chatterTechOps(List<ClientMemberCode__c> cmcList, String operationType) {
        List<ConnectApi.BatchInput> batchInputs = new List<ConnectApi.BatchInput>();
        CollaborationGroup chatterGroup = [SELECT Id, Name from CollaborationGroup WHERE Name = 'TechOps' LIMIT 1];
        for (ClientMemberCode__c cmc : cmcList) {
            if (operationType == 'Insert') {
                String inputText = '\nNew ' + 'Client Member Code ' + cmc.get('Name') +' has been created \n Code: ' + cmc.ClientMemberCode__c;
                ConnectApi.FeedItemInput feedItemInput = createFeed(inputText, chatterGroup.Id, cmc.Id);
                ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(feedItemInput);
                batchInputs.add(batchInput); 
            }
            else if (operationType == 'Delete') {
                String inputText = '\nClient Member Code ' + cmc.get('Name') +' has been deleted \n Code: ' + cmc.ClientMemberCode__c;
                ConnectApi.FeedItemInput feedItemInput = createFeed(inputText, chatterGroup.Id, cmc.Account_Id__c);
                ConnectApi.BatchInput batchInput = new ConnectApi.BatchInput(feedItemInput);
                batchInputs.add(batchInput);
            } 
        }
        ConnectApi.ChatterFeeds.postFeedElementBatch(Network.getNetworkId(), batchinputs);
    }
    
    public static ConnectApi.FeedItemInput createFeed(String inputText, Id mentionId, Id recordId) {
        ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
        ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
        ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
        ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();

        messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();

        mentionSegmentInput.id = mentionId;
        messageBodyInput.messageSegments.add(mentionSegmentInput);

        textSegmentInput.text = inputText;
        messageBodyInput.messageSegments.add(textSegmentInput);

        feedItemInput.body = messageBodyInput;
        feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
        feedItemInput.subjectId = recordId == null ? 'me' : recordId;
        return feedItemInput;
    }
}