src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Is_Cloned__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Cloned</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <description>Integrated with NetSuite and Redshift</description>
        <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Prediabetes</fullName>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Relationship__c.object
<CustomObject>
    <description>This junction object links Client with Partner Accounts, Partner Accounts with Client Opportunities, Client Accounts with Competitor Accounts, and Competitor Accounts with Client Opportunities.</description>
    <fields>
        <fullName>Contract_Partnership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The related Contract in a relationship between a deal and Partner.</description>
        <inlineHelpText>The related Contract in a relationship between a deal and Partner.</inlineHelpText>
        <label>Contract (P)</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Contract-Level Partnerships (Contract)</relationshipLabel>
        <relationshipName>ContractRelationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Contract_Partnership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to a Partner Account for linking a Partner Account to a Contract.</description>
        <inlineHelpText>Lookup to a Partner Account for linking a Partner Account to a Contract.</inlineHelpText>
        <label>Partner Account (C)</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contract-Level Partnership (Partner)</relationshipLabel>
        <relationshipName>Relationships4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipType__c</fullName>
        <description>Defines the type of relationship between two entities.</description>
        <inlineHelpText>Defines the type of relationship between two entities.</inlineHelpText>
        <label>Relationship Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Activity Tracking Devices</fullName>
                </value>
                <value>
                    <fullName>Associated Health Plan</fullName>
                </value>
                <value>
                    <fullName>Asthma</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Benefits Consultant</fullName>
                </value>
                <value>
                    <fullName>Billing Partner</fullName>
                </value>
                <value>
                    <fullName>Biometrics Screening/Health  Risk Assessment</fullName>
                </value>
                <value>
                    <fullName>Blue Cross Blue Shield Federal Employee Program</fullName>
                    <isActive>false</isActive>
                    <label>Blue Cross Blue Shield Federal Employee Program</label>
                </value>
                <value>
                    <fullName>Cardiovascular Health</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                </value>
                <value>
                    <fullName>Children&apos;s Health and Obesity</fullName>
                </value>
                <value>
                    <fullName>Cohort</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Concierge/Coaching Advocacy</fullName>
                </value>
                <value>
                    <fullName>Contract Path</fullName>
                </value>
                <value>
                    <fullName>Contract Terms</fullName>
                </value>
                <value>
                    <fullName>Cost Transparency</fullName>
                </value>
                <value>
                    <fullName>Data - Eligibility File</fullName>
                </value>
                <value>
                    <fullName>Data - Eligibility File - Historical</fullName>
                    <isActive>false</isActive>
                    <label>Data - Eligibility File - Historical</label>
                </value>
                <value>
                    <fullName>Data - Email</fullName>
                </value>
                <value>
                    <fullName>Data - Historical</fullName>
                    <isActive>false</isActive>
                    <label>Data - Historical</label>
                </value>
                <value>
                    <fullName>Data - Medical Claims</fullName>
                </value>
                <value>
                    <fullName>Data - N/A – No Livongo Marketing</fullName>
                </value>
                <value>
                    <fullName>Data - Other</fullName>
                </value>
                <value>
                    <fullName>Data - Pharmacy Claims</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List</fullName>
                    <isActive>false</isActive>
                    <label>Data - Predefined List</label>
                </value>
                <value>
                    <fullName>Data - Predefined List from Biometric</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from EMR</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from HRA</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from Medical Claims</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CloneListTest.cls
/*
	CloneListTest.cls
	
	Last Modified March 28 2019
	
	Test Class for CloneListUtil.cls and ChildRelationship.cls
*/
@isTest
public with sharing class CloneListTest {

	static testmethod void testCloneListControllerOne() {
		
        List<Account> allAccounts = new List<Account>();
        
        //Create client Account
        Account clientAccount = new Account();
        clientAccount.Name = 'Client Account';
        
        //Create partner Accounts
        Account partnerAccountOne = new Account();
        partnerAccountOne.Name = 'Partner Account 1';
        
        Account partnerAccountTwo = new Account();
        partnerAccountTwo.Name = 'Partner Account 2';
        
        allAccounts.add(clientAccount);
        allAccounts.add(partnerAccountOne);
        allAccounts.add(partnerAccountTwo);
        
        insert allAccounts;
        
        Id clientAccountId = [SELECT Id from Account WHERE Id = :clientAccount.Id].Id;
        
        //Create parent Client Overview record (this will be deep cloned)
        Contract testClientOverview = new Contract();
        testClientOverview.AccountId = clientAccountId;
		testClientOverview.name = 'Client Overview Record';
        testClientOverview.RecordTypeId = System.Label.Program_Agreement_Record_Type;
            
		insert testClientOverview;
        
        Id clientOverviewId = [SELECT ID FROM Contract WHERE Id = :testClientOverview.id].Id;
		
        List<Contract> programOverviews = new List<Contract>();
        
        //Insert related Program Overview Records
        Contract testProgramOverviewOne = new Contract();
		testProgramOverviewOne.name = 'Program Overview Record 1';
        testProgramOverviewOne.AccountId = clientAccountId;
        testProgramOverviewOne.Program_Name__c = 'Diabetes';
        testProgramOverviewOne.Client_Overview__c = clientOverviewId;
        testProgramOverviewOne.RecordTypeId = System.Label.Program_Schedule_Record_Type;
        
        Contract testProgramOverviewTwo = new Contract();
		testProgramOverviewTwo.name = 'Client Overview Record';
        testProgramOverviewTwo.AccountId = clientAccountId;
        testProgramOverviewTwo.Program_Name__c = 'Hypertension';
        testProgramOverviewTwo.Client_Overview__c = clientOverviewId;
        testProgramOverviewTwo.RecordTypeId = System.Label.Program_Schedule_Record_Type;

        programOverviews.add(testProgramOverviewOne);
        programOverviews.add(testProgramOverviewTwo);
        
		insert programOverviews;
        
        //Create Contract-level Partnership Relationship records
        List<Relationship__c> allRelationships = new List<Relationship__c>();
        
        Relationship__c testRelationshipOne = new Relationship__c();
		testRelationshipOne.RelationshipType__C = 'Activity Tracking Devices'; //Relationship Type should be "Contract Path"
        testRelationshipOne.Partner_Contract_Partnership__c = [select Id FROM Account WHERE Id = :partnerAccountOne.Id].Id;
		testRelationshipOne.Contract_Partnership__c = clientOverviewId;
		allRelationships.add(testRelationshipOne);       
        
        Relationship__c testRelationshipTwo = new Relationship__c();
		testRelationshipTwo.RelationshipType__C = 'Asthma'; //Relationship Type should be "Billing Partner"
        testRelationshipTwo.Partner_Contract_Partnership__c = [select Id FROM Account WHERE Id = :partnerAccountTwo.Id].Id;
		testRelationshipTwo.Contract_Partnership__c = clientOverviewId;
		allRelationships.add(testRelationshipTwo);
        
        insert allRelationships;

		Test.startTest();
        List<List<String>> testSourceInformation = new List<List<String>>();
        //Source Object Name, Child Object Name, Parent Id
        List<String> allInfo = new List<String>{'Contract', 'Contract, Relationship__c', string.valueof(clientOverviewId)};
        
            testSourceInformation.add(allInfo);
        
        List<String> clonedParentId = clientOverviewServices.copyChildRecords(testSourceInformation);
        Test.stopTest();
        Contract clonedParentRecord = [SELECT Name, Is_Cloned__c FROM Contract WHERE Id = :Id.valueOf(clonedParentId.get(0))];
        
        System.assertEquals(TRUE, clonedParentRecord.Is_Cloned__c);
        System.assertEquals(2, [SELECT Id FROM Contract WHERE Client_Overview__c = :Id.valueOf(clonedParentId.get(0))].size());
        System.assertEquals(2, [SELECT Id FROM Relationship__c WHERE RelationshipType__c = 'Contract Path'].size());
        System.assertEquals(2, [SELECT Id FROM Relationship__c WHERE RelationshipType__c = 'Billing Partner'].size());
        //System.assertNotEquals(null, clonedParentId);
		//System.debug(System.assertEquals(0, [select count() from Contact where AccountId =: testAccountTwo.Id]);
		
	}		
}