src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Actual_Launch_Date__c</fullName>
        <description>Integrated with Redshift</description>
        <inlineHelpText>Integrated with Redshift</inlineHelpText>
        <label>Initial Launch Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Complete_Per_Legal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Complete Per Legal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Outreach_Stratification__c</fullName>
        <description>Integrated with Redshift</description>
        <inlineHelpText>Integrated with Redshift</inlineHelpText>
        <label>Outreach Stratification</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                    <default>true</default>
                    <label>None</label>
                </value>
                <value>
                    <fullName>A</fullName>
                </value>
                <value>
                    <fullName>B</fullName>
                </value>
                <value>
                    <fullName>C</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Client_Overview</fullName>
        <active>true</active>
        <description>Represents the overarching Program Agreement between Livongo and Client + the Client&apos;s specific operational processes</description>
        <label>Client Overview</label>
    </recordTypes>
    <recordTypes>
        <fullName>Program_Overview</fullName>
        <active>true</active>
        <description>Represents the program-specific, Program Schedule under a Program Agreement + the Client&apos;s specific operational processes regarding the program</description>
        <label>Program Overview</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractTriggerHandler.cls
/**
* This class serves as a handler for the Contract trigger.
* Created : 05/13/2019
* @author Connor Gallaher - Slalom
*/

public class ContractTriggerHandler {
    public static final Id CLIENT_OVERVIEW_RT =  Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Client_Overview').getRecordTypeId(); 
    public static final Id PROGRAM_OVERVIEW_RT = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Program_Overview').getRecordTypeId();
    
    public static void handleContractAfterInsert(List<Contract> newContracts) {
        if (!Test.isRunningTest())
            ContractService.chatterTechOps(null, newContracts, null, 'Insert');
    }
    public static void handleContractUpdate(Map<Id, Contract> oldContracts, List<Contract> newContracts) {
        List<Contract> initialContractsToRenew = new List<Contract>();
        List<Contract> programsToUpdateHS = new List<Contract>();
        //Iterate through contracts to find the POs which are marked complete (TRUE)
        //AND which used to be marked incomplete previously (FALSE)
        //Note: This is because the SpringCM workflow unchecks (FALSE) the Complete Per Legal field at the beginning of the workflow
        //and rechecks (TRUE) the Complete Per Legal field at the end of the workflow
        for (Contract c : newContracts) {
            if (c.Complete_Per_Legal__c && (c.Complete_Per_Legal__c != oldContracts.get(c.Id).Complete_Per_Legal__c)) {
                initialContractsToRenew.add(c);
            }
            
            if (c.RecordTypeId == PROGRAM_OVERVIEW_RT && c.Actual_Launch_Date__c != null && c.Actual_Launch_Date__c != oldContracts.get(c.Id).Actual_Launch_Date__c ||
                c.Outreach_Stratification__c != null && c.Outreach_Stratification__c != oldContracts.get(c.Id).Outreach_Stratification__c) {
                    programsToUpdateHS.add(c);
            }
        }
        //Pass list of changed Contracts to ContractService class
        if (!initialContractsToRenew.isEmpty()) {
            ContractService.autoCreateRenewalOpportunities(initialContractsToRenew);
        }
        
        //Tracking Fields and notifying TechOps Chatter Group
        final List<Schema.FieldSetMember> contractTrackedFields = SObjectType.Contract.FieldSets.HistoryTracking.getFields();
        if (!contractTrackedFields.isEmpty()) {
            if (!Test.isRunningTest())
                ContractService.chatterTechOps(oldContracts, newContracts, contractTrackedFields, 'Update');    
        }
        
        if (!programsToUpdateHS.isEmpty()) {
            ContractService.updateHealthScores(programsToUpdateHS);
        }
    }
    //JENGA-1304 Users will not be able to delete the Client Overviews if there are any Program Overviews associated
    public static void handleContractDelete(List<Contract> oldContracts) {
        List<Contract> programOverviewList = [SELECT Id From Contract WHERE Client_Overview__c IN :oldContracts];
        for (Contract c: oldContracts) {
            Id contractRecordTypeId = Schema.SObjectType.Contract.getRecordTypeInfosByDeveloperName().get('Client_Overview').getRecordTypeId();
            if (c.RecordTypeId == contractRecordTypeId && programOverviewList.Size() > 0) {
                c.addError(System.Label.ClientOverviewDeleteMessage);
            }   
        }
    }
    public static void handleContractAfterDelete(Map<Id, Contract> oldContracts) {
        if (!Test.isRunningTest())
            ContractService.chatterTechOps(oldContracts, null, null, 'Delete');
    }
}