src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Path</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contracts (Contract Path)</relationshipLabel>
        <relationshipName>Contracts1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contract_Path__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Direct contracts, please select &quot;Livongo&quot;. Indicates the Contract Path for the Opportunity, and required for Opps to be closed won. Once an Opp is won, the Contract Path will be represented as a relationship associated to the Client Overview.</description>
        <inlineHelpText>Direct contracts, please select &quot;Livongo&quot;. Indicates the Contract Path for the Opportunity, and required for Opps to be closed won. Once an Opp is won, the Contract Path will be represented as a relationship associated to the Client Overview.</inlineHelpText>
        <label>Contract Path</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Contract Path must be a Partner Account.</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Partner Account</value>
            </filterItems>
            <infoMessage>Contract Path must be a Partner Account.</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Contract Path)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Path__c</fullName>
        <description>JENGA-986</description>
        <formula>Client_Overview__r.Contract_Path__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Path</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_Sub_Type__c</fullName>
        <label>Project Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Create Custom Report</fullName>
                    <isActive>false</isActive>
                    <label>Create Custom Report</label>
                </value>
                <value>
                    <fullName>Create Standard Report</fullName>
                    <isActive>false</isActive>
                    <label>Create Standard Report</label>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                    <isActive>false</isActive>
                    <label>Custom Report</label>
                </value>
                <value>
                    <fullName>Data Science: Coaching Data</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Coaching Data</label>
                </value>
                <value>
                    <fullName>Data Science: Creating Metabase Dashboard</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Creating Metabase Dashboard</label>
                </value>
                <value>
                    <fullName>Data Science: Performance Guarantee Analysis</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Performance Guarantee Analysis</label>
                </value>
                <value>
                    <fullName>Data Science: Report Format Change/Adding Fields</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Report Format Change/Adding Fields</label>
                </value>
                <value>
                    <fullName>Data Science: Report Re-Runs</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Report Re-Runs</label>
                </value>
                <value>
                    <fullName>Data Science: Turn Off or Suspend Reports</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Turn Off or Suspend Reports</label>
                </value>
                <value>
                    <fullName>Data Source Change</fullName>
                    <isActive>false</isActive>
                    <label>Data Source Change</label>
                </value>
                <value>
                    <fullName>DOPS: Add Email Addresses</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Add Email Addresses</label>
                </value>
                <value>
                    <fullName>DOPS: Ad Hoc Term File</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Ad Hoc Term File</label>
                </value>
                <value>
                    <fullName>DOPS: Analysis of Eligible Population</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Analysis of Eligible Population</label>
                </value>
                <value>
                    <fullName>DOPS: Compare Population Lists</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Compare Population Lists</label>
                </value>
                <value>
                    <fullName>DOPS: Complete Data Spec Form for Partners</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Complete Data Spec Form for Partners</label>
                </value>
                <value>
                    <fullName>DOPS: Complete Data Spec for Partners</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Complete Data Spec for Partners</label>
                </value>
                <value>
                    <fullName>DOPS: Data Quality Fix</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Data Quality Fix</label>
                </value>
                <value>
                    <fullName>DOPS: Investigate Member&apos;s Diagnosis Code</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Investigate Member&apos;s Diagnosis Code</label>
                </value>
                <value>
                    <fullName>DOPS: List of Eligible Population</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: List of Eligible Population</label>
                </value>
                <value>
                    <fullName>DOPS: Other / New</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Other / New</label>
                </value>
                <value>
                    <fullName>ENR MKTG: Whitelist Client Emails</fullName>
                    <isActive>false</isActive>
                    <label>ENR MKTG: Whitelist Client Emails</label>
                </value>
                <value>
                    <fullName>Direct &gt; 2,500 Employees</fullName>
                    <label>Enterprise</label>
                </value>
                <value>
                    <fullName>ESI HC 360</fullName>
                </value>
                <value>
                    <fullName>Express Scripts (ESI)</fullName>
                </value>
                <value>
                    <fullName>Incentive Setup and Reporting</fullName>
                </value>
                <value>
                    <fullName>Make Department Specific Request</fullName>
                    <isActive>false</isActive>
                    <label>Make Department Specific Request</label>
                </value>
                <value>
                    <fullName>Partner - CVS</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                    <isActive>false</isActive>
                    <label>Population Refresh</label>
                </value>
                <value>
                    <fullName>Select Partner Account - Parent Project</fullName>
                </value>
                <value>
                    <fullName>Downmarket</fullName>
                    <label>Select Partner Accounts</label>
                </value>
                <value>
                    <fullName>Select Partner Account - Sub Project</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Template_Category__c</fullName>
        <label>Project Template Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ad Hoc Requests</fullName>
                </value>
                <value>
                    <fullName>Data Operations Requests</fullName>
                </value>
                <value>
                    <fullName>Data Science Requests</fullName>
                </value>
                <value>
                    <fullName>Others</fullName>
                    <isActive>false</isActive>
                    <label>Others</label>
                </value>
                <value>
                    <fullName>Project Template</fullName>
                </value>
                <value>
                    <fullName>Information Technology</fullName>
                    <label>Technology Requests</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project_Template_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ad Hoc DS Request</fullName>
                    <isActive>false</isActive>
                    <label>Ad Hoc DS Request</label>
                </value>
                <value>
                    <fullName>Ad Hoc Request</fullName>
                    <isActive>false</isActive>
                    <label>Ad Hoc Request</label>
                </value>
                <value>
                    <fullName>Carrier/Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Client Incentives</fullName>
                </value>
                <value>
                    <fullName>CMC Migration/Deactivation</fullName>
                </value>
                <value>
                    <fullName>Convert SPA to Enterprise</fullName>
                </value>
                <value>
                    <fullName>Cross-Sell (New Program)</fullName>
                </value>
                <value>
                    <fullName>Data Operations Request</fullName>
                    <isActive>false</isActive>
                    <label>Data Operations Request</label>
                </value>
                <value>
                    <fullName>Data Science Request</fullName>
                    <isActive>false</isActive>
                    <label>Data Science Request</label>
                </value>
                <value>
                    <fullName>Data Source Change</fullName>
                </value>
                <value>
                    <fullName>Divestiture</fullName>
                </value>
                <value>
                    <fullName>Enterprise Client Termination</fullName>
                </value>
                <value>
                    <fullName>New Client / Contract Path</fullName>
                </value>
                <value>
                    <fullName>New Client CVS</fullName>
                    <isActive>false</isActive>
                    <label>New Client CVS</label>
                </value>
                <value>
                    <fullName>Population Expansion</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                    <isActive>false</isActive>
                    <label>Population Refresh</label>
                </value>
                <value>
                    <fullName>Report Request</fullName>
                    <isActive>false</isActive>
                    <label>Report Request</label>
                </value>
                <value>
                    <fullName>SPA Carrier/Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>SPA Client Termination</fullName>
                </value>
                <value>
                    <fullName>Whole Person Transition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_End__c</fullName>
        <description>Used to track the date of when the project is estimated (scheduled) to be completed. This date will update accordingly to accommodate any scheduling changes.</description>
        <label>Estimated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_Start__c</fullName>
        <description>Used to track the date of when the project is scheduled to start.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskRaySubProjectHandlerTest.cls
@IsTest
public class TaskRaySubProjectHandlerTest{
  @TestSetup
    public static void setupData() {
        Account acc = TestFactory.createDownmarketClientAccount();
        acc.Name = 'Test DownMarket1';
        insert acc;
        List<Account> acclist = new List<Account>();
        Account acc1 = new Account(Name = 'Test Acc1');
        Account acc2 = new Account(Name = 'Test Acc2');
        Account acc3 = new Account(Name = 'Test Acc3');
        accList.add(acc1);
        accList.add(acc2);
        accList.add(acc3);
        insert accList; 
        Contract clientOverview = TestFactory.createClientOverview();
        clientOverview.Name = 'Test CO';
        clientOverview.AccountId = acc1.Id;
        clientOverview.Contract_Path__c = acc.Id;
        insert clientOverview;
        Opportunity opp1 = TestFactory.createOpportunity();
        opp1.Name = 'Opp1';
        opp1.AccountId = acc1.Id;
        opp1.ContractId = clientOverview.Id;
        insert opp1;
        Opportunity opp2 = TestFactory.createOpportunity();
        opp2.Name = 'Opp2';
        opp2.AccountId = acc2.Id;
        opp2.ContractId = clientOverview.Id;
        insert opp2;
        Opportunity opp3 = TestFactory.createOpportunity();
        opp3.Name = 'opp3';
        opp3.AccountId = acc3.Id;
        opp3.ContractId = clientOverview.Id;
        insert opp3;
        TASKRAY__Project__c tp = new TASKRAY__Project__c(Name = 'Test CO - Select Partner Account',
                                                        Project_Type__c = 'New Client / Contract Path',
                                                        Project_Template_Category__c = 'Project Template',
                                                        Project_Sub_Type__c = 'Select Partner Account - Parent Project',
                                                        Client_Overview__c = clientOverview.Id,
                                                        TASKRAY__Project_Start__c = system.Today(),
                                                        TASKRAY__Project_End__c = system.Today() + 7,
                                                        TaskRayLaunchDate__c = system.today() + 7);
        insert tp;
        
        TASKRAY__Project__c tpsubProject = new TASKRAY__Project__c(Name = '[Template] Client Name - SPA Sub Project',
                                                         Project_Type__c = 'New Client / Contract Path',
                                                         Project_Template_Category__c = 'Project Template',
                                                         Project_Sub_Type__c = 'Select Partner Account - Sub Project',
                                                         TASKRAY__trTemplate__c = true);
       insert tpsubProject;        
    } 
    
    @isTest
    private static void createSubProjects(){
        TASKRAY__Project__c tp = [Select Id, Name,Project_Sub_Type__c,TASKRAY__Project_Start__c,TASKRAY__Project_End__c,
                                   TaskRayLaunchDate__c from TaskRay__Project__c where Name = 'Test CO - Select Partner Account' Limit 1];
        TASKRAY__Project__c tpsubProject = [Select Id from TASKRAY__Project__c where Name = '[Template] Client Name - SPA Sub Project' Limit 1];
        String templateId = tpsubProject.Id;
        List<String> templateIdlist = new List<String>();
        List<String> opIdList = new List<String>();
        List<List<String>> sourceList = new List<List<String>>();
        templateIdList.add(templateId);
        List<Opportunity> opps = [Select Id from opportunity where Name IN ('opp1', 'opp2','opp3') Limit 3];
        for(Opportunity op : opps){
            opIdList.add(op.Id);
        }
        opIdList.add(tp.Id);
        sourceList.add(opIdList);
        sourceList.add(templateIdList);
        Test.startTest();
        List<List<TaskRay__Project__c>> tpListFinals = new List<List<TaskRay__Project__c>>();
        tpListfinals = TaskRaySubProjectHandler.taskRayOpps(sourceList);
        Test.stopTest();
        System.assertNotEquals(null, tpListfinals);
        System.assertEquals(3, tpListfinals.get(0).size());
    }
}