src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Type__c</fullName>
        <label>Project Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project_Template_Category__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Ad Hoc DS Request</fullName>
                    <isActive>false</isActive>
                    <label>Ad Hoc DS Request</label>
                </value>
                <value>
                    <fullName>Ad Hoc Request</fullName>
                    <isActive>false</isActive>
                    <label>Ad Hoc Request</label>
                </value>
                <value>
                    <fullName>Carrier/Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>Client Incentives</fullName>
                </value>
                <value>
                    <fullName>CMC Migration/Deactivation</fullName>
                </value>
                <value>
                    <fullName>Convert SPA to Enterprise</fullName>
                </value>
                <value>
                    <fullName>Cross-Sell (New Program)</fullName>
                </value>
                <value>
                    <fullName>Data Operations Request</fullName>
                    <isActive>false</isActive>
                    <label>Data Operations Request</label>
                </value>
                <value>
                    <fullName>Data Science Request</fullName>
                    <isActive>false</isActive>
                    <label>Data Science Request</label>
                </value>
                <value>
                    <fullName>Data Source Change</fullName>
                </value>
                <value>
                    <fullName>Divestiture</fullName>
                </value>
                <value>
                    <fullName>Enterprise Client Termination</fullName>
                </value>
                <value>
                    <fullName>New Client / Contract Path</fullName>
                </value>
                <value>
                    <fullName>New Client CVS</fullName>
                    <isActive>false</isActive>
                    <label>New Client CVS</label>
                </value>
                <value>
                    <fullName>Population Expansion</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                    <isActive>false</isActive>
                    <label>Population Refresh</label>
                </value>
                <value>
                    <fullName>Report Request</fullName>
                    <isActive>false</isActive>
                    <label>Report Request</label>
                </value>
                <value>
                    <fullName>SPA Carrier/Contract Path Change</fullName>
                </value>
                <value>
                    <fullName>SPA Client Termination</fullName>
                </value>
                <value>
                    <fullName>Whole Person Transition</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskRayProjectTriggerHandler.cls
public with sharing class TaskRayProjectTriggerHandler {
    public static void handleProjectUpdate(Map<Id, TASKRAY__Project__c> oldProjects, List<TASKRAY__Project__c> newProjects) {
        List<TASKRAY__Project__c> projectListToCreateCHS = new List<TASKRAY__Project__c>();
        for (TASKRAY__Project__c project: newProjects) {
            if (project.Client_Overview__c != null && (project.Client_Overview__c != oldProjects.get(project.Id).Client_Overview__c)
                && project.Project_Type__c == 'New Client / Contract Path' || project.Project_Type__c == 'Carrier/Contract Path Change' ||
                project.Project_Type__c == 'Cross-Sell (New Program)') {
                projectListToCreateCHS.add(project);
            }
        }
        if (projectListToCreateCHS.size() > 0) {
            TaskRayProjectService.createClientHandoff(projectListToCreateCHS);
        }
    }
}