src/objects/Contract.object
<CustomObject>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Client Overview record to which an individual, program-specific Program Overview relates.</description>
        <inlineHelpText>The parent Client Overview contract record to which an individual, program-specific Program Overview relates. Integrated with Redshift.</inlineHelpText>
        <label>Client Overview</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>You must select a &quot;Client Overview&quot;</errorMessage>
            <filterItems>
                <field>Contract.RecordType.Name</field>
                <operation>equals</operation>
                <value>Client Overview</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>Program Overviews</relationshipLabel>
        <relationshipName>ProgramOverviews</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Device_Type__c</fullName>
        <label>New Device Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>HTAND</fullName>
                </value>
                <value>
                    <fullName>HT900</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <description>Integrated with NetSuite and Redshift</description>
        <inlineHelpText>Integrated with NetSuite and Redshift</inlineHelpText>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Prediabetes</fullName>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ContractHistortyTrackingTest.cls
/**
* This class contains the test methods for chatter posts made on the Contract Service Apex Class .
* Created : 07/08/2020
* @author Virinchi Bairisetty
*/
@isTest
public class ContractHistortyTrackingTest {
    public static final List<Schema.FieldSetMember> contractTrackedFields = SObjectType.Contract.FieldSets.HistoryTracking.getFields();
    @isTest(SeeAllData=true)
    static void contractHistoryTrackingInsertOperation() {
        List<Contract> newContracts = new List<Contract>();
        
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        
        Contract clientOverview = TestFactory.createClientOverview();
        clientOverview.AccountId = clientAccount.Id;
        insert clientOverview;
        
        Contract newProgramOverview = TestFactory.createProgramOverview();
        newProgramOverview.Program_Name__c = 'Diabetes';
        newProgramOverview.New_Device_Type__c = 'HTAND';
        newProgramOverview.Client_Overview__c = clientOverview.Id;
        newProgramOverview.AccountId = clientAccount.Id;
        newContracts.add(newProgramOverview);
        insert newContracts;
        
        ContractService.chatterTechOps(null, newContracts, null, 'Insert');
        system.assertEquals(1, newContracts.size());
    }
    
    @isTest(SeeAllData=true)
    static void contractHistoryTrackingDeleteOperation() {
        Map<Id, Contract> oldContracts = new Map<Id, Contract>();
        List<Contract> oldContractsList = new List<Contract>();
        
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
        
        Contract clientOverview = TestFactory.createClientOverview();
        clientOverview.AccountId = clientAccount.Id;
        insert clientOverview;
        
        Contract oldProgramOverview = TestFactory.createProgramOverview();
        oldProgramOverview.AccountId = clientAccount.Id;
        oldProgramOverview.Program_Name__c = 'Diabetes';
        oldProgramOverview.New_Device_Type__c = 'HTAND';
        oldProgramOverview.Client_Overview__c = clientOverview.Id;
        oldContractsList.add(oldProgramOverview);
        insert oldContractsList;
        
        for (Contract oldCon : oldContractsList) {
            oldContracts.put(oldCon.Id, oldCon);
        }
        
        ContractService.chatterTechOps(oldContracts, null, null, 'Delete');
        system.assertEquals(1, oldContracts.size());
    }
}