src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Scores</relationshipLabel>
        <relationshipName>Health_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Actual_Result__c</fullName>
        <label>Actual Result</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSM_Action_Steps__c</fullName>
        <label>CSM Action Steps</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Display_Fields__c</fullName>
        <label>Display Fields</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Element_Section__c</fullName>
        <label>Element Section</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Health_Segment__c</fullName>
        <label>Health Segment</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member Satisfaction</fullName>
                </value>
                <value>
                    <fullName>Enrollment</fullName>
                </value>
                <value>
                    <fullName>Activation</fullName>
                </value>
                <value>
                    <fullName>Active 30</fullName>
                </value>
                <value>
                    <fullName>Marketing Type (Outreach Stratification)</fullName>
                </value>
                <value>
                    <fullName>Email Coverage</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                </value>
                <value>
                    <fullName>eHba1c Reduction</fullName>
                </value>
                <value>
                    <fullName>ROI Status</fullName>
                </value>
                <value>
                    <fullName>Client Launch Date</fullName>
                </value>
                <value>
                    <fullName>Systolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Diastolic BP Reduction</fullName>
                </value>
                <value>
                    <fullName>Program Score</fullName>
                </value>
                <value>
                    <fullName>Renewal Timing</fullName>
                </value>
                <value>
                    <fullName>Cross Sells/Expansions</fullName>
                </value>
                <value>
                    <fullName>Client NPS</fullName>
                </value>
                <value>
                    <fullName>Interaction Cadence</fullName>
                </value>
                <value>
                    <fullName>Executive Sponsor Interaction/Engagement</fullName>
                </value>
                <value>
                    <fullName>Contract Path/Partner Relationship/Status</fullName>
                </value>
                <value>
                    <fullName>Client Business Health</fullName>
                </value>
                <value>
                    <fullName>Issues</fullName>
                </value>
                <value>
                    <fullName>Competitor w/in account</fullName>
                </value>
                <value>
                    <fullName>Immediate Action Needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Program__c</fullName>
        <label>Program</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Diabetes</fullName>
                </value>
                <value>
                    <fullName>Hypertension</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                    <isActive>false</isActive>
                    <label>Behavioral Health</label>
                </value>
                <value>
                    <fullName>Diabetes Prevention</fullName>
                    <isActive>false</isActive>
                    <label>Diabetes Prevention</label>
                </value>
                <value>
                    <fullName>Weight Management</fullName>
                    <isActive>false</isActive>
                    <label>Weight Management</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Recommended_Action_Steps__c</fullName>
        <label>Recommended Action Steps</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountHealthScoreController.cls
public with sharing class AccountHealthScoreController {

    public static Map<String,List<AccountHealthScoreHelper>> accMap = new Map<String,List<AccountHealthScoreHelper>>();
    public static Map<String, List<AccountHealthScoreHelper>> dmMap = new Map<String,List<AccountHealthScoreHelper>>();
    public static Map<String, List<AccountHealthScoreHelper>> htnMap = new Map<String,List<AccountHealthScoreHelper>>();

    @AuraEnabled(cacheable=true)
    public static accountHealthScoreWrapper getHealthScores(Id accountId) {

        List<Health_Score__c> healthScoresList = [SELECT Id, Account__c, Program__c, Actual_Result__c, Score__c, CSM_Action_Steps__c, Element_Section__c, Health_Segment__c, 
                                                    Recommended_Action_Steps__c, RecordType.Name, Display_Fields__c FROM Health_Score__c WHERE Account__c = :accountId Order By Sort_Order__c ASC];

        for(Health_Score__c hs: healthScoresList) {
            if(hs.RecordType.Name == 'Account Health Score') {
                generateMap(hs,accMap);
            }
            else if (hs.RecordType.Name == 'Program Health Score') {
                if(hs.Program__c == 'Diabetes') {
                    generateMap(hs, dmMap);
                }
                else if(hs.Program__c == 'Hypertension') {
                    generateMap(hs, htnMap);
                }
            }
        }
        AccountHealthScoreWrapper accountHealthScoreWrapper = new AccountHealthScoreWrapper();
        accountHealthScoreWrapper.accountScoreMap = accMap;
        accountHealthScoreWrapper.dmScoreMap = dmMap;
        accountHealthScoreWrapper.htnScoreMap = htnMap;

        return accountHealthScoreWrapper;
    }

    public static void generateMap(Health_Score__c hsRecord, Map<String, List<AccountHealthScoreHelper>> healthMap) {
        if(healthMap.containsKey(hsRecord.Element_Section__c)) {
            List<AccountHealthScoreHelper> hsList = healthMap.get(hsRecord.Element_Section__c);
            AccountHealthScoreHelper hsHelper;
            hsHelper = new AccountHealthScoreHelper(hsRecord);
            hsList.add(hsHelper);
            healthMap.put(hsRecord.Element_Section__c, hsList);
        }
        else {
            AccountHealthScoreHelper hsHelper1;
            hsHelper1 = new AccountHealthScoreHelper(hsRecord);
            healthMap.put(hsRecord.Element_Section__c, new List<AccountHealthScoreHelper> {hsHelper1});
        }
    } 

    public class accountHealthScoreWrapper{
        @AuraEnabled
        public Map<String,List<AccountHealthScoreHelper>> accountScoreMap {get; set;}
        @AuraEnabled
        public Map<String,List<AccountHealthScoreHelper>> dmScoreMap {get; set;}
        @AuraEnabled
        public Map<String,List<AccountHealthScoreHelper>> htnScoreMap {get; set;}
    }

    public class AccountHealthScoreHelper {
        @AuraEnabled public Id hsId {get; set;}
        @AuraEnabled public Decimal score {get; set;}
        @AuraEnabled public String hsSegement {get; set;}
        @AuraEnabled public List<String> displayFields {get; set;} 

        public AccountHealthScoreHelper(Health_Score__c hs){
            this.hsId = hs.Id;
            this.score = hs.Score__c;
            this.hsSegement = hs.Health_Segment__c;
            if(hs.Display_Fields__c != null) {
                this.displayFields = hs.Display_Fields__c.split(',');
            }
        }
    }
}