src/objects/Health_Score__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Health Scores</relationshipLabel>
        <relationshipName>Health_Scores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Health Score</label>
    <nameField>
        <displayFormat>HS-{00000000}</displayFormat>
        <label>Health Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Health Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AccountHealthScoreControllerTest.cls
@isTest
public class AccountHealthScoreControllerTest {
    @TestSetup
    static void setupData() {
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;
    }
    
    private static Account getClientAccount() {
        return [SELECT Id FROM Account LIMIT 1];
    }
    
    private static List<Health_Score__c> getHealthScores(Id accId) {
        return [SELECT Id FROM Health_Score__c WHERE Account__c = :accId];
    }
	
    @isTest
    static void hsControllerTest() {
        Account acc = getClientAccount();
        Test.startTest();
        AccountHealthScoreController.getHealthScores(acc.Id);
        Test.stopTest();
        List<Health_Score__c> hsList = getHealthScores(acc.Id);
        system.assertEquals(32, hsList.size());
    }
}