src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Covered_Lives__c</fullName>
        <label>Opportunity Covered Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Bypass_Sales_Price_Validation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Bypass Sales Price Validation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gross_Program_ARR_Copy__c</fullName>
        <label>Gross Program ARR Copy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Program_ARR__c</fullName>
        <formula>CASE(
    Program_Family__c,

    &apos;Diabetes&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.25 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                (0.20 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),
    
    &apos;Hypertension&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                    (0.08 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),

    &apos;Weight Management&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
                         IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
                         IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), 0.10 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                         0.08 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12))),
    
    &apos;Prediabetes&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
                    IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
                    IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), 0.10 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                    0.08 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c* Incremental_Sales_Price__c * 12))),

    Product_Participants__c * UnitPrice * 12 + Product_Participants__c * 0.02 * PMPM__c * 6
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Program ARR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Program_TCV_Copy__c</fullName>
        <description>Renamed to EVA - JENGA-1540</description>
        <label>Gross Program EVA Copy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Program_TCV__c</fullName>
        <formula>CASE(Program_Family__c,
        &apos;Diabetes&apos;, Product_Participants__c * 0.25 * UnitPrice * Quantity + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity,
        &apos;Hypertension&apos;, Product_Participants__c * 0.10 * UnitPrice * Quantity + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity,
        &apos;Weight Management&apos;, IF(UnitPrice == 1.00, 
                                (500 * Product_Participants__c * 0.10 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity, 
                                (Product_Participants__c * 0.10 * UnitPrice * 12 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity), 
        &apos;Prediabetes&apos;, IF(UnitPrice == 1.00, 
                            (500 * Product_Participants__c * 0.10 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity, 
                            (Product_Participants__c * 0.10 * UnitPrice * 12 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity),
        Product_Participants__c * UnitPrice * Quantity + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Program EVA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>OpportunityProductName__c</fullName>
        <label>Opportunity Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book ID</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Structure__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
        <label>Pricing Structure</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Pricing Structure is not available.</errorMessage>
            <filterItems>
                <field>Pricing_Structure__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program_ID__c</valueField>
            </filterItems>
            <filterItems>
                <field>Pricing_Structure__c.Price_Book__c</field>
                <operation>equals</operation>
                <valueField>$Source.Price_Book_ID__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pricing_Structure__c</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Participants__c</fullName>
        <inlineHelpText>For new opportunities, enter estimated recruitables or rPwX. For renewals, enter enrolled members.</inlineHelpText>
        <label>Program Participants (rPwX or Enrolled)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_ARR_Copy__c</fullName>
        <description>Workflow field update will populate this field with the value from Program ARR; this field will then be rolled up into value on Opportunity</description>
        <label>Program ARR Copy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_ARR__c</fullName>
        <formula>CASE(
Program_Family__c,

&apos;Diabetes&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.25 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.20 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),

&apos;Hypertension&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.08 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),

&apos;Weight Management&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.08 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12))),

&apos;Prediabetes&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.08 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12))),

(Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Product_Participants__c * 0.02 * PMPM__c * 6
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Program ARR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Pricing_Structure__c.object
<CustomObject>
    <label>Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Participant__mdt.object
<CustomObject>
    <description>Jenga#1448 - Opp wizard enhancement. Created a mapping between program and participants percentage based on opp covered lives.</description>
    <fields>
        <fullName>ParticipantPercentage__c</fullName>
        <label>ParticipantPercentage</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Program Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Livongo for Diabetes</fullName>
                </value>
                <value>
                    <fullName>Livongo for Hypertension</fullName>
                </value>
                <value>
                    <fullName>Livongo for Weight Management</fullName>
                </value>
                <value>
                    <fullName>Livongo Diabetes Prevention Program</fullName>
                </value>
                <value>
                    <fullName>Livongo for Behavioral Health by myStrength 1.0</fullName>
                </value>
                <value>
                    <fullName>Livongo for Behavioral Health by myStrength 2.0</fullName>
                </value>
                <value>
                    <fullName>DM Solution</fullName>
                </value>
                <value>
                    <fullName>DP Solution</fullName>
                </value>
                <value>
                    <fullName>CV Solution</fullName>
                </value>
                <value>
                    <fullName>CV + DM</fullName>
                </value>
                <value>
                    <fullName>CV + DP</fullName>
                </value>
                <value>
                    <fullName>CV + DM + DP</fullName>
                </value>
                <value>
                    <fullName>Teladoc Telehealth Services</fullName>
                </value>
                <value>
                    <fullName>Teladoc Expert Medical Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Participant</label>
    <pluralLabel>Program Participants</pluralLabel>
</CustomObject>

src/classes/OpportunityLineItemServiceTest.cls
@isTest
public with sharing class OpportunityLineItemServiceTest {
    
    public static final String DM_SOLUTION = System.Label.DM_Solution;
    public static final String CV_SOLUTION = System.Label.CV_Solution;
    public static final String DP_SOLUTION = System.Label.DP_Solution;
    public static Map<String, Decimal> programToParticipantPercentMap = new Map<String, Decimal>();
    
    @TestSetup
    static void testData(){
        Account clientAccount = TestFactory.createClientAccount();
        insert clientAccount;      
        
        Opportunity newBusinessOpp = TestFactory.createTypeBasedOpportunity('New Business');
        newBusinessOpp.AccountId = clientAccount.Id;
        newBusinessOpp.Opportunity_Covered_Lives__c=10000;     
        insert newBusinessOpp;
        
        Pricebook2 livongoPricebook = TestFactory.createPricebook();
        insert livongoPricebook;
        
        List<Product2> programsList = new List<Product2>();
        programsList.add(TestFactory.createProgram('Livongo for Diabetes'));
        programsList.add(TestFactory.createProgram('Livongo for Hypertension'));
        programsList.add(TestFactory.createProgram('Livongo Diabetes Prevention Program'));
        programsList.add(TestFactory.createProgram('Livongo for Weight Management'));
        programsList.add(TestFactory.createProgram('Livongo for Behavioral Health by myStrength 2.0'));
        programsList.add(TestFactory.createWPProgram(CV_SOLUTION, 'Hypertension'));
        insert programsList;
        
        Id standardPBId = Test.getStandardPricebookId();
        
        List<PricebookEntry> entriesList = new List<PricebookEntry>();
        List<PricebookEntry> livongoPBEntriesList = new List<PricebookEntry>();
        List<Pricing_Structure__c> pricingStructureList = new List<Pricing_Structure__c>();
        
        for(Product2 program: programsList) {
            entriesList.add(TestFactory.createPricebookEntry(standardPBId, program.Id));
            livongoPBEntriesList.add(TestFactory.createPricebookEntry(livongoPricebook.Id, program.Id));
            pricingStructureList.add(TestFactory.createPricingStructure(livongoPricebook.Id, program.Id));
        }        
        insert entriesList;
        insert livongoPBEntriesList;
        insert pricingStructureList;
        
        List<OpportunityLineItem> oliList = new List<OpportunityLineItem>();
        
        for(PricebookEntry pbe: livongoPBEntriesList) {
            oliList.add(TestFactory.createOpportunityLineItem(newBusinessOpp.Id, pbe.Id));
        }   
        insert oliList;        
    }
    
    private static Opportunity getOpportunity() {
        return [SELECT Id,Opportunity_Covered_Lives__c FROM Opportunity LIMIT 1];
    }
    
    private static Pricebook2 getPricebook() {
        return [SELECT Id, Name FROM Pricebook2 WHERE Name = 'Livongo'];
    }    
    
    private static List<OpportunityLineItem> getOLI() {
        return [SELECT Id, Program_ID__c, OpportunityProductName__c, Opportunity.Opportunity_Covered_Lives__c, Product_Participants__c,
                Pricing_Structure__c, Quantity, UnitPrice, Gross_Program_ARR__c, Gross_Program_ARR_Copy__c, Program_ARR__c, Program_ARR_Copy__c, 
                Gross_Program_TCV__c, Gross_Program_TCV_Copy__c, Bypass_Sales_Price_Validation__c FROM OpportunityLineItem];
    }
    
    
    static {
        Map<String, Decimal> ppMap = new Map<String, Decimal>();
        Program_Participant__mdt[] ppMDT = [SELECT Program_Name__c, ParticipantPercentage__c FROM Program_Participant__mdt];
        for (Program_Participant__mdt pp: ppMDT) {
            ppMap.put(pp.Program_Name__c, pp.ParticipantPercentage__c);
        }
        programToParticipantPercentMap = ppMap;        
    }
    
    @isTest
    static void calculateProgramParticipantsTest() {
        Opportunity opp=getOpportunity();               
        List<List<OpportunityLineItem>> OppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<List<OpportunityLineItem>> finalOppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<OpportunityLineItem> oliList = getOLI();        
        OppLineItemList.add(oliList);       
        Test.startTest();
        finalOppLineItemList = OpportunityLineItemService.calculateProgramParticipants(OppLineItemList);
        Test.stopTest();
        
        system.assertEquals(6, finalOppLineItemList[0].size());        
        for (OpportunityLineItem finalList: finalOppLineItemList[0]) {              
            if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == CV_SOLUTION){
                system.assertEquals((programToParticipantPercentMap.get(CV_SOLUTION) * opp.Opportunity_Covered_Lives__c) , finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == 'Livongo for Diabetes'){
                system.assertEquals((programToParticipantPercentMap.get('Livongo for Diabetes') * opp.Opportunity_Covered_Lives__c), finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == 'Livongo for Hypertension'){
                system.assertEquals((programToParticipantPercentMap.get('Livongo for Hypertension') * opp.Opportunity_Covered_Lives__c), finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == 'Livongo for Weight Management'){
                system.assertEquals((programToParticipantPercentMap.get('Livongo for Weight Management') * opp.Opportunity_Covered_Lives__c), finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == 'Livongo Diabetes Prevention Program'){
                system.assertEquals((programToParticipantPercentMap.get('Livongo Diabetes Prevention Program') * opp.Opportunity_Covered_Lives__c), finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == 'Livongo for Behavioral Health by myStrength 2.0'){
                system.assertEquals(opp.Opportunity_Covered_Lives__c, finalList.Product_Participants__c);
            }            
        }     
    }
    
    @isTest
    static void calculateProgramParticipantsTest1() {
        Opportunity opp = getOpportunity();
        List<List<OpportunityLineItem>> OppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<List<OpportunityLineItem>> finalOppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<OpportunityLineItem> oliList = getOLI();
        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        Pricebook2 livongoPricebook = getPricebook();
        Id standardPBId = Test.getStandardPricebookId();
        
        Product2 wpProgram = TestFactory.createWPProgram(DM_SOLUTION, 'Diabetes');
        insert wpProgram;
        
        PricebookEntry standardPbe = TestFactory.createPricebookEntry(standardPBId, wpProgram.Id);
        PricebookEntry pbe = TestFactory.createPricebookEntry(livongoPricebook.Id, wpProgram.Id);
        
        pbeList.add(standardPbe);
        pbeList.add(pbe);
        insert pbeList;
        
        OpportunityLineItem oli = TestFactory.createOpportunityLineItem(opp.Id, pbe.Id);
        oli.Price_Book_ID__c = pbe.Pricebook2Id;
        oli.Program_ID__c = pbe.Product2Id;
        insert oli;
        
        oliList.add(oli);
        
        OppLineItemList.add(OLIList);
        
        Test.startTest();
        finalOppLineItemList = OpportunityLineItemService.calculateProgramParticipants(OppLineItemList);
        Test.stopTest();
        
        for (OpportunityLineItem finalList: finalOppLineItemList[0]) {
            if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == CV_SOLUTION){
                system.assertEquals((programToParticipantPercentMap.get('CV + DM') * opp.Opportunity_Covered_Lives__c) , finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == DM_SOLUTION){
                system.assertEquals((programToParticipantPercentMap.get(DM_SOLUTION) * opp.Opportunity_Covered_Lives__c) , finalList.Product_Participants__c);
            }
        }
    }
    
    @isTest
    static void calculateProgramParticipantsTest2() {
        Opportunity opp = getOpportunity();
        List<List<OpportunityLineItem>> OppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<List<OpportunityLineItem>> finalOppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<OpportunityLineItem> oliList = getOLI();
        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        Pricebook2 livongoPricebook = getPricebook();
        Id standardPBId = Test.getStandardPricebookId();
        
        Product2 wpProgram = TestFactory.createWPProgram(DP_SOLUTION, 'Prediabetes');
        insert wpProgram;
        
        PricebookEntry standardPbe = TestFactory.createPricebookEntry(standardPBId, wpProgram.Id);
        PricebookEntry pbe = TestFactory.createPricebookEntry(livongoPricebook.Id, wpProgram.Id);
        
        pbeList.add(standardPbe);
        pbeList.add(pbe);
        insert pbeList;
        
        OpportunityLineItem oli = TestFactory.createOpportunityLineItem(opp.Id, pbe.Id);
        oli.Price_Book_ID__c = pbe.Pricebook2Id;
        oli.Program_ID__c = pbe.Product2Id;
        insert oli;
        
        oliList.add(oli);
        
        OppLineItemList.add(oliList);
        
        Test.startTest();
        finalOppLineItemList = OpportunityLineItemService.calculateProgramParticipants(OppLineItemList);
        Test.stopTest();
        
        for (OpportunityLineItem finalList: finalOppLineItemList[0]) {
            if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == CV_SOLUTION){
                system.assertEquals((programToParticipantPercentMap.get('CV + DP') * opp.Opportunity_Covered_Lives__c) , finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == DM_SOLUTION){
                system.assertEquals((programToParticipantPercentMap.get(DM_SOLUTION) * opp.Opportunity_Covered_Lives__c) , finalList.Product_Participants__c);
            }else if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == DP_SOLUTION){
                system.assertEquals((programToParticipantPercentMap.get(DP_SOLUTION) * opp.Opportunity_Covered_Lives__c) , finalList.Product_Participants__c);
            }
        }
    }
    
    @isTest
    static void calculateProgramParticipantsTest3() {
        Opportunity opp = getOpportunity();
        List<List<OpportunityLineItem>> OppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<List<OpportunityLineItem>> finalOppLineItemList = new List<List<OpportunityLineItem>>(); 
        List<OpportunityLineItem> oliList = getOLI();
        List<PricebookEntry> standardPbeList = new List<PricebookEntry>();
        List<PricebookEntry> pbeList = new List<PricebookEntry>();
        Pricebook2 livongoPricebook = getPricebook();
        Id standardPBId = Test.getStandardPricebookId();
        List<Product2> wpPrograms = new List<Product2>();
        
        wpPrograms.add(TestFactory.createWPProgram(DM_SOLUTION, 'Diabetes'));
        wpPrograms.add(TestFactory.createWPProgram(DP_SOLUTION, 'Prediabetes'));
        insert wpPrograms;
        
        for (Product2 program: wpPrograms) {
            standardPbeList.add(TestFactory.createPricebookEntry(standardPBId, program.Id));
            pbeList.add(TestFactory.createPricebookEntry(livongoPricebook.Id, program.Id));
        }
        
        insert standardPbeList;
        insert pbeList;
        
        for (PricebookEntry pbe: pbeList) {
            OpportunityLineItem oli = TestFactory.createOpportunityLineItem(opp.Id, pbe.Id);
            oli.Price_Book_ID__c = pbe.Pricebook2Id;
            oli.Program_ID__c = pbe.Product2Id;
            oliList.add(oli);
        }
        
        upsert oliList;
        
        OppLineItemList.add(oliList);
        
        Test.startTest();
        finalOppLineItemList = OpportunityLineItemService.calculateProgramParticipants(OppLineItemList);
        Test.stopTest();
        
        for (OpportunityLineItem finalList: finalOppLineItemList[0]) {           
            if(finalList.OpportunityProductName__c!= null && finalList.OpportunityProductName__c == CV_SOLUTION){
                system.assertEquals((programToParticipantPercentMap.get('CV + DM + DP') * opp.Opportunity_Covered_Lives__c) , finalList.Product_Participants__c);
            }
        }        
    }
    
    @isTest
    static void opportunityLineItemTriggerHandlerTest() {
        List<OpportunityLineItem> oppLineItemList = getOLI();
        for (OpportunityLineItem oli: oppLineItemList) {
            oli.Quantity = 12;
            oli.UnitPrice = 50;
            oli.Bypass_Sales_Price_Validation__c = True;
        }
        update oppLineItemList;
    }
}