src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Gross_Program_ARR_Copy__c</fullName>
        <label>Gross Program ARR Copy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Program_ARR__c</fullName>
        <formula>CASE(
    Program_Family__c,

    &apos;Diabetes&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.25 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                (0.20 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),
    
    &apos;Hypertension&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                    (0.08 * Product_Participants__c * (UnitPrice * 12)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),

    &apos;Weight Management&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
                         IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
                         IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), 0.10 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                         0.08 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12))),
    
    &apos;Prediabetes&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
                    IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
                    IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), 0.10 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
                    0.08 * Product_Participants__c * UnitPrice * 12 + Currently_Enrolled_Members__c* Incremental_Sales_Price__c * 12))),

    Product_Participants__c * UnitPrice * 12 + Product_Participants__c * 0.02 * PMPM__c * 6
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Program ARR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Program_TCV_Copy__c</fullName>
        <description>Renamed to EVA - JENGA-1540</description>
        <label>Gross Program EVA Copy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Gross_Program_TCV__c</fullName>
        <formula>CASE(Program_Family__c,
        &apos;Diabetes&apos;, Product_Participants__c * 0.25 * UnitPrice * Quantity + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity,
        &apos;Hypertension&apos;, Product_Participants__c * 0.10 * UnitPrice * Quantity + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity,
        &apos;Weight Management&apos;, IF(UnitPrice == 1.00, 
                                (500 * Product_Participants__c * 0.10 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity, 
                                (Product_Participants__c * 0.10 * UnitPrice * 12 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity), 
        &apos;Prediabetes&apos;, IF(UnitPrice == 1.00, 
                            (500 * Product_Participants__c * 0.10 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity, 
                            (Product_Participants__c * 0.10 * UnitPrice * 12 + Product_Participants__c * 0.10 * Year_2_Price__c * MAX(Quantity - 12, 0)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity),
        Product_Participants__c * UnitPrice * Quantity + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * Quantity)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gross Program EVA</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_ARR_Copy__c</fullName>
        <description>Workflow field update will populate this field with the value from Program ARR; this field will then be rolled up into value on Opportunity</description>
        <label>Program ARR Copy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Program_ARR__c</fullName>
        <formula>CASE(
Program_Family__c,

&apos;Diabetes&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.25 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.20 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),

&apos;Hypertension&apos;, IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.08 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12),

&apos;Weight Management&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.08 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12))),

&apos;Prediabetes&apos;, IF(AND(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), UnitPrice == 1.00), 608 * Product_Participants__c * 0.10,
IF(UnitPrice == 1.00, 608 * Product_Participants__c * 0.08,
IF(CONTAINS(Opportunity.Opp_Owner_Role__c, &apos;Commercial&apos;), (0.10 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12,
(0.08 * Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Currently_Enrolled_Members__c * Incremental_Sales_Price__c * 12))),

(Product_Participants__c * ((UnitPrice - (Estimated_At_Risk_PPPM__c + Estimated_Partner_Admin_Fees__c)) * 12 + Up_Front_Per_Member__c)) + Product_Participants__c * 0.02 * PMPM__c * 6
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Net Program ARR</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/OpportunityLineItemTriggerHandler.cls
/**
* This is the TriggerHandler Class for the OpportunityLineItem Trigger.
* Created : 10/09/2020
* @author : Virinchi Bairisetty
*/
public class OpportunityLineItemTriggerHandler {
    //Method to update ARR and TCV formula fields into the ARR and TCV Copy fields which will be used to roll-up on the Opportuntiy.
    public static void handleOpportunityLineItemInsert(List<OpportunityLineItem> newOppLineList) {
        for (OpportunityLineItem oppLine: newOppLineList) {
            if (oppLine.Gross_Program_ARR__c  != null) {
                oppLine.Gross_Program_ARR_Copy__c = oppLine.Gross_Program_ARR__c;
            }
            if (oppLine.Program_ARR__c != null) {
                oppLine.Program_ARR_Copy__c = oppLine.Program_ARR__c;
            }
            if (oppLine.Gross_Program_TCV__c != null) {
                oppLine.Gross_Program_TCV_Copy__c = oppLine.Gross_Program_TCV__c;
            }
        }
    }
    
    //Method to update ARR and TCV formula fields into the ARR and TCV Copy fields which will be used to roll-up on the Opportuntiy.
    public static void handleOpportunityLineItemUpdate(Map<Id, OpportunityLineItem> oldOppLineMap, List<OpportunityLineItem> newOppLineList) {
        for (OpportunityLineItem oppLine: newOppLineList) {
            if (oppLine.Gross_Program_ARR__c  != null && oppLine.Gross_Program_ARR__c != oldOppLineMap.get(oppLine.Id).Gross_Program_ARR__c) {
                oppLine.Gross_Program_ARR_Copy__c = oppLine.Gross_Program_ARR__c;
            }
            if (oppLine.Program_ARR__c != null && oppLine.Program_ARR__c != oldOppLineMap.get(oppLine.Id).Program_ARR__c) {
                oppLine.Program_ARR_Copy__c = oppLine.Program_ARR__c;
            }
            if (oppLine.Gross_Program_TCV__c != null && oppLine.Gross_Program_TCV__c != oldOppLineMap.get(oppLine.Id).Gross_Program_TCV__c) {
                oppLine.Gross_Program_TCV_Copy__c = oppLine.Gross_Program_TCV__c;
            }
        }
    }
}