src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Opportunity_Covered_Lives__c</fullName>
        <label>Opportunity Covered Lives</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>OpportunityProductName__c</fullName>
        <label>Opportunity Product Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Book_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Price Book ID</label>
        <referenceTo>Pricebook2</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pricing_Structure__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <inlineHelpText>Updating Pricing Structure will overwrite the Sales Price, Estimated At-Risk PPPM, Estimated Partner Admin Fees, and Up Front Per Member fields.</inlineHelpText>
        <label>Pricing Structure</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Pricing Structure is not available.</errorMessage>
            <filterItems>
                <field>Pricing_Structure__c.Program__c</field>
                <operation>equals</operation>
                <valueField>$Source.Program_ID__c</valueField>
            </filterItems>
            <filterItems>
                <field>Pricing_Structure__c.Price_Book__c</field>
                <operation>equals</operation>
                <valueField>$Source.Price_Book_ID__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Pricing_Structure__c</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Participants__c</fullName>
        <inlineHelpText>For new opportunities, enter estimated recruitables or rPwX. For renewals, enter enrolled members.</inlineHelpText>
        <label>Program Participants (rPwX or Enrolled)</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Program ID</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Opportunity Program</relationshipLabel>
        <relationshipName>Opportunity_Program</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Pricing_Structure__c.object
<CustomObject>
    <label>Pricing Structure</label>
    <nameField>
        <label>Pricing Structure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pricing Structures</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Whole_Person_Solution__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check only if the program is a WP Solution.</inlineHelpText>
        <label>Whole Person Solution</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Program_Participant__mdt.object
<CustomObject>
    <description>Jenga#1448 - Opp wizard enhancement. Created a mapping between program and participants percentage based on opp covered lives.</description>
    <fields>
        <fullName>ParticipantPercentage__c</fullName>
        <label>ParticipantPercentage</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Program_Name__c</fullName>
        <label>Program Name</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Livongo for Diabetes</fullName>
                </value>
                <value>
                    <fullName>Livongo for Hypertension</fullName>
                </value>
                <value>
                    <fullName>Livongo for Weight Management</fullName>
                </value>
                <value>
                    <fullName>Livongo Diabetes Prevention Program</fullName>
                </value>
                <value>
                    <fullName>Livongo for Behavioral Health by myStrength 1.0</fullName>
                </value>
                <value>
                    <fullName>Livongo for Behavioral Health by myStrength 2.0</fullName>
                </value>
                <value>
                    <fullName>DM Solution</fullName>
                </value>
                <value>
                    <fullName>DP Solution</fullName>
                </value>
                <value>
                    <fullName>CV Solution</fullName>
                </value>
                <value>
                    <fullName>CV + DM</fullName>
                </value>
                <value>
                    <fullName>CV + DP</fullName>
                </value>
                <value>
                    <fullName>CV + DM + DP</fullName>
                </value>
                <value>
                    <fullName>Teladoc Telehealth Services</fullName>
                </value>
                <value>
                    <fullName>Teladoc Expert Medical Services</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Program Participant</label>
    <pluralLabel>Program Participants</pluralLabel>
</CustomObject>

src/classes/OpportunityLineItemService.cls
public without sharing class OpportunityLineItemService {
    public static final String DM_SOLUTION = System.Label.DM_Solution;
    public static final String CV_SOLUTION = System.Label.CV_Solution;
    public static final String DP_SOLUTION = System.Label.DP_Solution;
    public static Map<String, Decimal> programToParticipantPercentMap = new Map<String, Decimal>();
    
    static {
        Map<String, Decimal> ppMap = new Map<String, Decimal>();
        Program_Participant__mdt[] ppMDT = [SELECT Program_Name__c, ParticipantPercentage__c FROM Program_Participant__mdt];
        for (Program_Participant__mdt pp: ppMDT) {
            ppMap.put(pp.Program_Name__c, pp.ParticipantPercentage__c);
        }
        programToParticipantPercentMap = ppMap;        
    }
    
    @InvocableMethod(label='Calculate Program Participant')
    public static List<List<OpportunityLineItem>> calculateProgramParticipants(List<List<OpportunityLineItem>> oliList) {
        //Get the OpportunityLineItem Information
        List<OpportunityLineItem> OppLineItemlist=new List<OpportunityLineItem>();
        List<List<OpportunityLineItem>> finalOppLineItemList = new List<List<OpportunityLineItem>>();
        OppLineItemlist=oliList[0];         
        Set<Id> oliIds = new Set<Id>();
        for (OpportunityLineItem l : OppLineItemlist) {
            oliIds.add(l.Id);
        }
        
        List<OpportunityLineItem> lineItemList = [SELECT Id, Program_ID__c, OpportunityProductName__c, Opportunity.Opportunity_Covered_Lives__c, Product_Participants__c,
                                                  Price_Book_ID__r.Name, Pricing_Structure__c, Quantity, Product2.Whole_Person_Solution__c, OpportunityId FROM OpportunityLineItem WHERE Id IN :oliIds];
        //Add Unique Programs to Set
        Set<String> programNameSet = new Set<String>();
        for (OpportunityLineItem lineItem: lineItemList) {
            programNameSet.add(lineItem.OpportunityProductName__c);
        }
        
        for (OpportunityLineItem oli: lineItemList) {
            if (oli.Opportunity.Opportunity_Covered_Lives__c != null) {                
                if (oli.OpportunityProductName__c  == CV_SOLUTION) {
                    if (programNameSet.contains(DM_SOLUTION) && programNameSet.contains(DP_SOLUTION)) {
                        oli.Product_Participants__c = programToParticipantPercentMap.get('CV + DM + DP') * oli.Opportunity.Opportunity_Covered_Lives__c;                        
                    }
                    else if (programNameSet.contains(DM_SOLUTION)) {
                        oli.Product_Participants__c = programToParticipantPercentMap.get('CV + DM') * oli.Opportunity.Opportunity_Covered_Lives__c; 
                    }
                    else if (programNameSet.contains(DP_SOLUTION)) {
                        oli.Product_Participants__c =programToParticipantPercentMap.get('CV + DP') * oli.Opportunity.Opportunity_Covered_Lives__c; 
                    }
                    else {
                        oli.Product_Participants__c = programToParticipantPercentMap.get(oli.OpportunityProductName__c) * oli.Opportunity.Opportunity_Covered_Lives__c;
                    }
                }
                else if (programToParticipantPercentMap.get(oli.OpportunityProductName__c) != null) {
                    oli.Product_Participants__c = programToParticipantPercentMap.get(oli.OpportunityProductName__c) * oli.Opportunity.Opportunity_Covered_Lives__c;
                }
                if(oli.Product_Participants__c != null){
                   oli.Product_Participants__c = oli.Product_Participants__c.round();                   
                }
            }            
        }
        finalOppLineItemList.add(lineItemList);          
        return finalOppLineItemList;
    }      
}