src/objects/Relationship__c.object
<CustomObject>
    <description>This junction object links Client with Partner Accounts, Partner Accounts with Client Opportunities, Client Accounts with Competitor Accounts, and Competitor Accounts with Client Opportunities.</description>
    <fields>
        <fullName>Master_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Lookup to either a Partner or Competitor Account for linking to a Client Account.</description>
        <inlineHelpText>Lookup to either a Partner or Competitor Account for linking to a Client Account.</inlineHelpText>
        <label>Master Vendor Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Master Vendor Accounts</relationshipLabel>
        <relationshipName>PartnerAccounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Master_Client_Account_Name__c</fullName>
        <formula>Master_Client_Account__r.Name</formula>
        <label>Master Client Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Master_Client_Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Defines the master account for the Relates To record</description>
        <label>Master Client Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Master Client Accounts</relationshipLabel>
        <relationshipName>MasterAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RelationshipType__c</fullName>
        <description>Defines the type of relationship between two entities.</description>
        <inlineHelpText>Defines the type of relationship between two entities.</inlineHelpText>
        <label>Relationship Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Activity Tracking Devices</fullName>
                </value>
                <value>
                    <fullName>Associated Health Plan</fullName>
                </value>
                <value>
                    <fullName>Asthma</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Benefits Consultant</fullName>
                </value>
                <value>
                    <fullName>Billing Partner</fullName>
                </value>
                <value>
                    <fullName>Biometrics Screening/Health  Risk Assessment</fullName>
                </value>
                <value>
                    <fullName>Blue Cross Blue Shield Federal Employee Program</fullName>
                    <isActive>false</isActive>
                    <label>Blue Cross Blue Shield Federal Employee Program</label>
                </value>
                <value>
                    <fullName>Cardiovascular Health</fullName>
                </value>
                <value>
                    <fullName>Care Coordinator</fullName>
                </value>
                <value>
                    <fullName>Children&apos;s Health and Obesity</fullName>
                </value>
                <value>
                    <fullName>Cohort</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Concierge/Coaching Advocacy</fullName>
                </value>
                <value>
                    <fullName>Contract Path</fullName>
                </value>
                <value>
                    <fullName>Contract Terms</fullName>
                </value>
                <value>
                    <fullName>Cost Transparency</fullName>
                </value>
                <value>
                    <fullName>Data - Eligibility File</fullName>
                </value>
                <value>
                    <fullName>Data - Eligibility File - Historical</fullName>
                    <isActive>false</isActive>
                    <label>Data - Eligibility File - Historical</label>
                </value>
                <value>
                    <fullName>Data - Email</fullName>
                </value>
                <value>
                    <fullName>Data - Historical</fullName>
                    <isActive>false</isActive>
                    <label>Data - Historical</label>
                </value>
                <value>
                    <fullName>Data - Medical Claims</fullName>
                </value>
                <value>
                    <fullName>Data - N/A – No Livongo Marketing</fullName>
                </value>
                <value>
                    <fullName>Data - Other</fullName>
                </value>
                <value>
                    <fullName>Data - Pharmacy Claims</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List</fullName>
                    <isActive>false</isActive>
                    <label>Data - Predefined List</label>
                </value>
                <value>
                    <fullName>Data - Predefined List from Biometric</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from EMR</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from HRA</fullName>
                </value>
                <value>
                    <fullName>Data - Predefined List from Medical Claims</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <displayFormat>R-{0000000}</displayFormat>
        <label>Relationship Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <recordTypes>
        <fullName>Contract_Partnership</fullName>
        <active>true</active>
        <description>Partner at the Contract level (Admin Party, Billing Partner, Care Coordinator, Contract Path, Contract Terms, or Data)</description>
        <label>Contract Partnership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RelatedClientAccountsCtrl.cls
/**
* This class serves as the Apex controller for the RelatedClientAccounts Lightning Component bundle.
* Created : 06/11/2019
* @author Connor Gallaher - Slalom
*/

public class RelatedClientAccountsCtrl {
    /*
     * The partnerAccountId will be passed in from the Partner Agreement Wizard Flow;
     * Returns a list of Relationships that will be accessible and selectable within the Flow.
	 */
    @AuraEnabled
    public static List<Relationship__c> getRelatedClientAccounts(Id partnerAccountId) {
        Id contractPartnershipRT = Schema.SObjectType.Relationship__c.getRecordTypeInfosByDeveloperName().get('Contract_Partnership').getRecordTypeId();
        return [SELECT Id, RecordTypeId, RelationshipType__c, Master_Account__c, Master_Client_Account__c, Master_Client_Account_Name__c FROM Relationship__c WHERE Master_Account__c = :partnerAccountId AND RecordTypeId = :contractPartnershipRT ORDER BY RelationshipType__c ASC];
    }
}