src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>Client_Overview__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Client Overview</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>TaskRay_Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Sub_Type__c</fullName>
        <label>Project Sub-Type</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Project_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Create Custom Report</fullName>
                    <isActive>false</isActive>
                    <label>Create Custom Report</label>
                </value>
                <value>
                    <fullName>Create Standard Report</fullName>
                    <isActive>false</isActive>
                    <label>Create Standard Report</label>
                </value>
                <value>
                    <fullName>Custom Report</fullName>
                    <isActive>false</isActive>
                    <label>Custom Report</label>
                </value>
                <value>
                    <fullName>Data Science: Coaching Data</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Coaching Data</label>
                </value>
                <value>
                    <fullName>Data Science: Creating Metabase Dashboard</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Creating Metabase Dashboard</label>
                </value>
                <value>
                    <fullName>Data Science: Performance Guarantee Analysis</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Performance Guarantee Analysis</label>
                </value>
                <value>
                    <fullName>Data Science: Report Format Change/Adding Fields</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Report Format Change/Adding Fields</label>
                </value>
                <value>
                    <fullName>Data Science: Report Re-Runs</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Report Re-Runs</label>
                </value>
                <value>
                    <fullName>Data Science: Turn Off or Suspend Reports</fullName>
                    <isActive>false</isActive>
                    <label>Data Science: Turn Off or Suspend Reports</label>
                </value>
                <value>
                    <fullName>Data Source Change</fullName>
                    <isActive>false</isActive>
                    <label>Data Source Change</label>
                </value>
                <value>
                    <fullName>DOPS: Add Email Addresses</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Add Email Addresses</label>
                </value>
                <value>
                    <fullName>DOPS: Ad Hoc Term File</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Ad Hoc Term File</label>
                </value>
                <value>
                    <fullName>DOPS: Analysis of Eligible Population</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Analysis of Eligible Population</label>
                </value>
                <value>
                    <fullName>DOPS: Compare Population Lists</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Compare Population Lists</label>
                </value>
                <value>
                    <fullName>DOPS: Complete Data Spec Form for Partners</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Complete Data Spec Form for Partners</label>
                </value>
                <value>
                    <fullName>DOPS: Complete Data Spec for Partners</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Complete Data Spec for Partners</label>
                </value>
                <value>
                    <fullName>DOPS: Data Quality Fix</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Data Quality Fix</label>
                </value>
                <value>
                    <fullName>DOPS: Investigate Member&apos;s Diagnosis Code</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Investigate Member&apos;s Diagnosis Code</label>
                </value>
                <value>
                    <fullName>DOPS: List of Eligible Population</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: List of Eligible Population</label>
                </value>
                <value>
                    <fullName>DOPS: Other / New</fullName>
                    <isActive>false</isActive>
                    <label>DOPS: Other / New</label>
                </value>
                <value>
                    <fullName>ENR MKTG: Whitelist Client Emails</fullName>
                    <isActive>false</isActive>
                    <label>ENR MKTG: Whitelist Client Emails</label>
                </value>
                <value>
                    <fullName>Direct &gt; 2,500 Employees</fullName>
                    <label>Enterprise</label>
                </value>
                <value>
                    <fullName>ESI HC 360</fullName>
                </value>
                <value>
                    <fullName>Express Scripts (ESI)</fullName>
                </value>
                <value>
                    <fullName>Incentive Setup and Reporting</fullName>
                </value>
                <value>
                    <fullName>Make Department Specific Request</fullName>
                    <isActive>false</isActive>
                    <label>Make Department Specific Request</label>
                </value>
                <value>
                    <fullName>Partner - CVS</fullName>
                </value>
                <value>
                    <fullName>Population Refresh</fullName>
                    <isActive>false</isActive>
                    <label>Population Refresh</label>
                </value>
                <value>
                    <fullName>Select Partner Account - Parent Project</fullName>
                </value>
                <value>
                    <fullName>Downmarket</fullName>
                    <label>Select Partner Accounts</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_End__c</fullName>
        <description>Used to track the date of when the project is estimated (scheduled) to be completed. This date will update accordingly to accommodate any scheduling changes.</description>
        <label>Estimated End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Parent Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipLabel>Child Projects</relationshipLabel>
        <relationshipName>Project_Parent</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__Project_Start__c</fullName>
        <description>Used to track the date of when the project is scheduled to start.</description>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectOpportunity</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskRayLaunchDate__c</fullName>
        <description>Due date of the Task Ray task</description>
        <label>Launch Date / Due Date</label>
        <type>Date</type>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskRaySubProjectHandler.cls
global class TaskRaySubProjectHandler{
    
    public static final String PROJECT_SUB_TYPE = 'Select Partner Account - Parent Project';
    @InvocableMethod
    public static List<List<TaskRay__Project__c>> taskRayOpps(List<List<String>> sourceInfoList){
        system.debug('SourceInforList::: ' + sourceInfoList);
        Map<String,Map<String,Object>> projectInfo = new Map<String,Map<String,Object>>();
        List<Id> OppIdList = new List<Id>();
        String templateId;
        String parentProjectId;
        String newProjectName = '';
        String newSubProjectName = '[Template] Client Name - SPA Sub Project';
        String clientOverviewId;        
        templateId = System.label.TaskRayTemplateId;
        oppIdList = sourceInfoList.get(0);
        parentProjectId = oppIdList.remove(oppIdList.size()-1);
        if(Test.isRunningTest()){
            templateId = sourceInfoList.get(1).get(0);   
        }
        List<Opportunity> oppList = [Select Id, Account.Name,ContractId  from Opportunity where Id IN: oppIdList];
        clientOverviewId = oppList[0].ContractId;
        TaskRay__Project__c tp = [Select Id, TaskRayLaunchDate__c,TASKRAY__Project_Start__c, TASKRAY__Project_End__c
                                  from TaskRay__Project__c where Client_Overview__c =: clientOverviewId and 
                                  Project_Sub_Type__c =: PROJECT_SUB_TYPE and Id =:parentProjectId Limit 1];
        for(Opportunity opp: oppList){
            Map<String,Object> projectDetails = new Map<String,Object>();
            newProjectName = newSubProjectName.replace('[Template] Client Name',opp.Account.Name);
            projectDetails.put('templateProjectId',templateId);
            projectDetails.put('newName',newProjectName);
            projectDetails.put('depCloneBasedOnProjectStart', true);
            if(tp != Null && tp.TASKRAY__Project_Start__c != Null){
               projectDetails.put('newStartDate',tp.TASKRAY__Project_Start__c); 
            }
            projectDetails.put('contextRecordId', opp.Id);
            projectInfo.put(opp.Id,projectDetails);
        }
        try {
        Map<String,Object> cloneOptions = new Map<String,Object>();
        cloneOptions.put('assignInactiveToCurrent', true);  
        Map<String,Id> retInfo = TASKRAY.trTaskBoardController.cloneProjectsReturnIds(projectInfo, cloneOptions);
        List<TaskRay__Project__c> tpList = [Select Id, Name, TASKRAY__trOpportunity__c, TASKRAY__Project_Parent__c from 
                                            TaskRay__Project__c where ID IN: retInfo.values()]; 
        List<List<TaskRay__Project__c>> tpListFinal = new List<List<TaskRay__Project__c>>();
        tpListFinal.add(tpList);
        return tpListFinal;
        }
        catch (Exception e){
            System.debug('An unexpected error occured ' + e.getMessage());
            return null;            
        }
    } 
}