src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Entered for LinkedIn Sales Navigator Team Edition</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project_Task__c.object
<CustomObject>
    <description>This is the primary TaskRay object for tasks.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>TASKRAY__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TaskRay Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskRayTaskService.cls
/**
* This class contains the primary business logic for the TaskRayTask object, outside of what's contained in the managed package.
* Created : 06/11/2019
* @author Connor Gallaher - Slalom
*/

public class TaskRayTaskService {

    //Pulling ID of System Administrator in; want to post as this User to prevent
    //other users from deleting post(s).
    public static final Id SYS_ADMIN_ID = Id.valueOf(System.Label.System_Admin_Id);
    
    /*
    * Posts a Chatter feed item to the parent TaskRay Project associated with each task.
    */
    public static void postToParentProject(List<TASKRAY__Project_Task__c> tasks) {
        List<String> parameters;
        String chatterPostTemplate = System.Label.TaskRay_Chatter_Post_Message;

        List<FeedItem> feedItems = new List<FeedItem>();
        FeedItem item;
        for (TASKRAY__Project_Task__c task : tasks) {
            item = new FeedItem();
            item.ParentId = task.TASKRAY__Project__c;
            item.CreatedById = SYS_ADMIN_ID;
            parameters = new List<String>{task.Name, UserInfo.getName()};
            String postText = String.format(chatterPostTemplate, parameters);
            item.Body = postText;
            feedItems.add(item);
        }
        if (!feedItems.isEmpty()) {
            insert feedItems;
        }
    }
}