src/objects/Task.object
<CustomObject>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Entered for LinkedIn Sales Navigator Team Edition</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project__c.object
<CustomObject>
    <description>This is the primary TaskRay object for projects.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Projects</relationshipLabel>
        <relationshipName>trProjectAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TaskRayStatus__c</fullName>
        <description>The status of the TaskRay Project</description>
        <label>Project Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>In Progress - On Track</fullName>
                </value>
                <value>
                    <fullName>In Progress - Delayed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Contracting</fullName>
                    <isActive>false</isActive>
                    <label>Contracting</label>
                </value>
                <value>
                    <fullName>Implementation</fullName>
                    <isActive>false</isActive>
                    <label>Implementation</label>
                </value>
                <value>
                    <fullName>Launched + 90</fullName>
                    <isActive>false</isActive>
                    <label>Launched + 90</label>
                </value>
                <value>
                    <fullName>Ongoing Delivery</fullName>
                    <isActive>false</isActive>
                    <label>Ongoing Delivery</label>
                </value>
                <value>
                    <fullName>Terminated</fullName>
                    <isActive>false</isActive>
                    <label>Terminated</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TaskRay Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TASKRAY__Project_Task__c.object
<CustomObject>
    <description>This is the primary TaskRay object for tasks.  This object may be used to manage reports, dashboards, workflows and other native Salesforce functionality.</description>
    <fields>
        <fullName>TASKRAY__List__c</fullName>
        <label>List</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting on Dev Work</fullName>
                    <color>#CC66CC</color>
                    <label>Waiting on Dev Work</label>
                </value>
                <value>
                    <fullName>Not Started</fullName>
                    <color>#BBBBBB</color>
                    <default>true</default>
                    <label>Not Started</label>
                </value>
                <value>
                    <fullName>On Deck</fullName>
                    <color>#33FFFF</color>
                    <label>On Deck</label>
                </value>
                <value>
                    <fullName>In Progress On Track</fullName>
                    <color>#E27001</color>
                    <label>In Progress On Track</label>
                </value>
                <value>
                    <fullName>In Progress Delayed</fullName>
                    <color>#3366FF</color>
                    <label>In Progress Delayed</label>
                </value>
                <value>
                    <fullName>QA/UAT</fullName>
                    <color>#A845DC</color>
                    <label>QA/UAT/Code Review</label>
                </value>
                <value>
                    <fullName>Complete</fullName>
                    <color>#33CC00</color>
                    <label>Complete</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TASKRAY__Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>TASKRAY__Project__c</referenceTo>
        <relationshipName>Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TASKRAY__trAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>TaskRay Tasks</relationshipLabel>
        <relationshipName>trTaskAccount</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>TaskRay Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TaskRay Tasks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TaskRayTaskTriggerTest.cls
@isTest
public class TaskRayTaskTriggerTest {
    @testSetup
    static void setupData() {

        TASKRAY__Project__c project = new TASKRAY__Project__c();
        project.Name = 'Test TaskRay Project';
        project.TaskRayStatus__c = 'Not Started';
        insert project;

        Account testAccount = TestFactory.createClientAccount();
        insert testAccount;

        TASKRAY__Project_Task__c task1 = new TASKRAY__Project_Task__c();
        task1.Name = 'Test TaskRay Task 1';
        task1.TASKRAY__trAccount__c = testAccount.Id;
        task1.TASKRAY__List__c = 'Not Started';
        task1.TASKRAY__Project__c = project.Id;

        TASKRAY__Project_Task__c task2 = new TASKRAY__Project_Task__c();
        task2.Name = 'Test TaskRay Task 2';
        task2.TASKRAY__trAccount__c = testAccount.Id;
        task2.TASKRAY__List__c = 'Not Started';
        task2.TASKRAY__Project__c = project.Id;

        TASKRAY__Project_Task__c task3 = new TASKRAY__Project_Task__c();
        task3.Name = 'Test TaskRay Task 3';
        task3.TASKRAY__trAccount__c = testAccount.Id;
        task3.TASKRAY__List__c = 'Not Started';
        task3.TASKRAY__Project__c = project.Id;

        List<TASKRAY__Project_Task__c> tasks = new List<TASKRAY__Project_Task__c>();
        tasks.add(task1);
        tasks.add(task2);
        tasks.add(task3);
        insert tasks;
        
    }
    
    @isTest
    static void taskRayTaskDeleteTest() {
        
        TASKRAY__Project__c project = [SELECT Id FROM TASKRAY__Project__c LIMIT 1];
        
        List<TASKRAY__Project_Task__c> tasks = [SELECT Name, TASKRAY__trAccount__c, TASKRAY__List__c, TASKRAY__Project__c FROM TASKRAY__Project_Task__c];
                
        Test.startTest();

        delete tasks;

        Test.stopTest();

        List<FeedItem> feedItems = [SELECT Id, Body, ParentId, CreatedById FROM FeedItem];
        System.assertEquals(3, feedItems.size());
        for (FeedItem item : feedItems) {
            System.assertEquals(System.Label.System_Admin_Id, item.CreatedById);
            System.assertEquals(project.Id, item.ParentId);
        }
    }
}